export default async function (_ctx: Context, _session: Session | null, _opts?: {}) {
    return [
        "(() => {",
        "  if (window.__hyperUiControlInstalled) return;",
        "  window.__hyperUiControlInstalled = true;",
        "  window.__hyperUiControlReady = true;",
        "",
        "  const postResult = async (payload) => {",
        "    try {",
        "      await fetch('/ui/eval/result', {",
        "        method: 'POST',",
        "        headers: { 'content-type': 'application/json' },",
        "        body: JSON.stringify(payload),",
        "      });",
        "    } catch {}",
        "  };",
        "",
        "  const actions = {",
        "    ping: async () => ({ pong: true, at: Date.now() }),",
        "    location: async () => ({ href: location.href, path: location.pathname, search: location.search, hash: location.hash }),",
        "    selectionText: async () => String(window.getSelection?.() ?? ''),",
        "  };",
        "",
        "  const notify = (ev) => {",
        "    const box = document.createElement('div');",
        "    box.className = 'fixed right-4 top-4 z-[1000] max-w-sm rounded border bg-white shadow px-3 py-2 text-sm';",
        "    if (ev.level === 'error') box.classList.add('border-red-300', 'text-red-700');",
        "    else if (ev.level === 'warn') box.classList.add('border-yellow-300', 'text-yellow-800');",
        "    else box.classList.add('border-gray-300', 'text-gray-800');",
        "    if (ev.html) box.innerHTML = ev.html;",
        "    else box.textContent = ev.message ?? ev.text ?? '';",
        "    document.body.appendChild(box);",
        "    setTimeout(() => box.remove(), 2500);",
        "  };",
        "",
        "  const evalRan = new Set();",
        "  const handleEval = async (ev) => {",
        "    try {",
        "      const value = await (0, eval)(ev.code);",
        "      await postResult({ id: ev.id, ok: true, value });",
        "    } catch (error) {",
        "      await postResult({ id: ev.id, ok: false, error: String(error?.message ?? error) });",
        "    }",
        "  };",
        "",
        "  const handleAction = async (ev) => {",
        "    const fn = actions[ev.name];",
        "    if (!fn) {",
        "      await postResult({ id: ev.id, ok: false, error: 'unknown action: ' + ev.name });",
        "      return;",
        "    }",
        "    try {",
        "      const value = await fn(ev.args ?? null, ev);",
        "      await postResult({ id: ev.id, ok: true, value });",
        "    } catch (error) {",
        "      await postResult({ id: ev.id, ok: false, error: String(error?.message ?? error) });",
        "    }",
        "  };",
        "",
        "  const applyEvent = (ev) => {",
        "    if (!ev || typeof ev !== 'object') return;",
        "    if (ev.type === 'ui.navigate' && typeof ev.path === 'string') {",
        "      window.location.assign(ev.path);",
        "      return;",
        "    }",
        "    if (ev.type === 'ui.notify') {",
        "      notify(ev);",
        "      return;",
        "    }",
        "    if (ev.type === 'ui.eval' && typeof ev.code === 'string' && typeof ev.id === 'string') {",
        "      void handleEval(ev);",
        "      return;",
        "    }",
        "    if (ev.type === 'ui.action' && typeof ev.name === 'string' && typeof ev.id === 'string') {",
        "      void handleAction(ev);",
        "    }",
        "    // screen.eval: the server pushes code down the stream; this tab runs",
        "    // it and answers at POST /screen/result. Each id runs once (the server",
        "    // re-sends into a connect gap); a tab without window.page keeps quiet;",
        "    // a hidden tab yields so the visible one answers first.",
        "    if (ev.type === 'eval' && typeof ev.id === 'number' && typeof ev.code === 'string') {",
        "      void (async () => {",
        "        if (evalRan.has(ev.id)) return;",
        "        evalRan.add(ev.id);",
        "        if (!window.page) return;",
        "        if (document.hidden) await new Promise(r => setTimeout(r, 400));",
        "        let body;",
        "        try {",
        "          const value = await new Function('return (async () => { ' + ev.code + ' })()')();",
        "          body = { id: ev.id, value: value === undefined ? null : value };",
        "        } catch (err) {",
        "          body = { id: ev.id, error: String(err) };",
        "        }",
        "        fetch('/screen/result', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });",
        "      })();",
        "      return;",
        "    }",
        "    // Chat freshness: a new event for the agent this tab shows fires",
        "    // 'hyper-tick' — the #msg-tail htmx trigger — so the transcript",
        "    // updates instantly instead of waiting for the 10s fallback poll.",
        "    if (ev.type === 'agent.event_appended' && ev.agentId === document.body.dataset.agentId) {",
        "      document.body.dispatchEvent(new Event('hyper-tick'));",
        "    }",
        "  };",
        "",
        "  window.__hyperUiApplyEvent = applyEvent;",
        "",
        "  // procs/events/client.js re-dispatches every SSE message as a",
        "  // 'hyper-events' DOM event — that is our transport now (the old build",
        "  // monkey-patched window.EventSource instead).",
        "  document.addEventListener('hyper-events', (e) => applyEvent(e.detail));",
        "  document.addEventListener('hyper-ui-event', (e) => applyEvent(e.detail));",
        "})();",
    ].join('\n');
}
