export default async function (_ctx: Context, _session: Session | null, _opts?: {}) {
    return [
        "(() => {",
        "  if (window.__hyperUiControlInstalled) return;",
        "  window.__hyperUiControlInstalled = true;",
        "  window.__hyperUiControlReady = true;",
        "",
        "  const postResult = async (payload) => {",
        "    try {",
        "      await fetch('/ui/eval/result', {",
        "        method: 'POST',",
        "        headers: { 'content-type': 'application/json' },",
        "        body: JSON.stringify(payload),",
        "      });",
        "    } catch {}",
        "  };",
        "",
        "  const actions = {",
        "    ping: async () => ({ pong: true, at: Date.now() }),",
        "    location: async () => ({ href: location.href, path: location.pathname, search: location.search, hash: location.hash }),",
        "    selectionText: async () => String(window.getSelection?.() ?? ''),",
        "  };",
        "",
        "  // secure-input markup and form lifecycle are HTMX/server-owned. SSE",
        "  // only signals the persistent host to fetch its current fragment.",
        "  let secureInputReturnFocus = null;",
        "  const secureInputRefresh = () => {",
        "    const active = document.activeElement;",
        "    if (active && active !== document.body && !document.getElementById('app-popup')?.contains(active)) secureInputReturnFocus = active;",
        "    document.body.dispatchEvent(new Event('secure-input-refresh'));",
        "  };",
        "  document.body.addEventListener('htmx:afterSwap', event => {",
        "    const target = document.getElementById('app-popup-body');",
        "    if (event.detail?.target !== target) return;",,
        "    const secure = event.detail.target.querySelector('[data-secure-input]');",
        "    if (secure) { secure.querySelector('input')?.focus(); return; }",
        "    const target = secureInputReturnFocus?.isConnected ? secureInputReturnFocus : document.getElementById('input');",
        "    target?.focus(); secureInputReturnFocus = null;",
        "  });",
        "",
        "  // Toasts stack in the bottom-right corner. They used to be absolutely",
        "  // positioned at top-right one on top of another, so two notifications",
        "  // in the same second hid each other. A stack also puts the newest",
        "  // nearest the corner your eye already returns to.",
        "  const toastHost = () => {",
        "    let host = document.getElementById('toasts');",
        "    if (!host) {",
        "      host = document.createElement('div');",
        "      host.id = 'toasts';",
        "      host.className = 'fixed bottom-4 right-4 z-[1000] flex flex-col-reverse gap-2 items-end pointer-events-none';",
        "      document.body.appendChild(host);",
        "    }",
        "    return host;",
        "  };",
        "",
        "  const TOAST_STYLE = {",
        "    // Everything goes away by itself; an error simply gets long enough",
        "    // to be read. A toast that waits forever becomes a pile of stale",
        "    // bad news you have to clear by hand.",
        "    error: { cls: 'border-red-200 bg-red-50 text-red-800', icon: 'ph-warning-circle', ms: 20000 },",
        "    warn:  { cls: 'border-amber-200 bg-amber-50 text-amber-900', icon: 'ph-warning', ms: 8000 },",
        "    info:  { cls: 'border-gray-200 bg-white text-gray-800', icon: 'ph-info', ms: 4000 },",
        "  };",
        "",
        "  const notify = (ev) => {",
        "    const style = TOAST_STYLE[ev.level] || TOAST_STYLE.info;",
        "    const box = document.createElement('div');",
        "    box.className = 'pointer-events-auto flex max-w-sm items-start gap-2 rounded-xl border px-3 py-2 text-sm shadow-lg cursor-pointer transition duration-200 translate-y-2 opacity-0 ' + style.cls;",
        "    const icon = document.createElement('i');",
        "    icon.className = 'ph ' + style.icon + ' mt-0.5 shrink-0';",
        "    const body = document.createElement('div');",
        "    body.className = 'min-w-0 break-words';",
        "    if (ev.html) body.innerHTML = ev.html;",
        "    else body.textContent = ev.message ?? ev.text ?? '';",
        "    box.append(icon, body);",
        "    // The detail, if any: clamped to a few lines so a stack trace does",
        "    // not take over the screen, and expandable in place — the whole",
        "    // point of carrying it here is that nobody has to go hunting.",
        "    let detail = null;",
        "    if (ev.bodyHtml || ev.body) {",
        "      detail = document.createElement('div');",
        "      detail.className = 'toast-detail mt-1 max-h-28 overflow-hidden text-[11px] leading-snug';",
        "      if (ev.bodyHtml) detail.innerHTML = ev.bodyHtml;",
        "      else {",
        "        const pre = document.createElement('pre');",
        "        pre.className = 'whitespace-pre-wrap break-words font-mono opacity-80';",
        "        pre.textContent = String(ev.body);",
        "        detail.appendChild(pre);",
        "      }",
        "      body.appendChild(detail);",
        "    }",
        "    toastHost().appendChild(box);",
        "    requestAnimationFrame(() => box.classList.remove('translate-y-2', 'opacity-0'));",
        "    const dismiss = () => {",
        "      // Never snatch a toast out from under a reader: if the pointer is",
        "      // on it, wait and try again.",
        "      if (hovering) { setTimeout(dismiss, 1500); return; }",
        "      box.classList.add('translate-y-2', 'opacity-0');",
        "      setTimeout(() => box.remove(), 200);",
        "    };",
        "    // With a detail the first click opens it fully and the next closes",
        "    // the toast: reading and dismissing are different intentions, and",
        "    // one click should not do both.",
        "    let expanded = false;",
        "    let hovering = false;",
        "    box.addEventListener('mouseenter', () => { hovering = true; });",
        "    box.addEventListener('mouseleave', () => { hovering = false; });",
        "    box.addEventListener('click', () => {",
        "      if (detail && !expanded && detail.scrollHeight > detail.clientHeight) {",
        "        expanded = true;",
        "        detail.classList.remove('max-h-28', 'overflow-hidden');",
        "        detail.classList.add('max-h-80', 'overflow-y-auto');",
        "        return;",
        "      }",
        "      dismiss();",
        "    });",
        "    // An error waits to be dismissed by hand: it is the one thing that",
        "    // must not vanish while you are looking somewhere else.",
        "    // A toast you opened yourself lingers, but not forever.",
        "    setTimeout(dismiss, ev.sticky ? 60000 : style.ms);",
        "    return dismiss;",
        "  };",
        "",
        "  // Anything on the page can raise a toast — the chat does it when you",
        "  // click a tool circle. One implementation, one corner.",
        "  window.toast = notify;",
        "",
        "  const evalRan = new Set();",
        "  const handleEval = async (ev) => {",
        "    try {",
        "      const value = await (0, eval)(ev.code);",
        "      await postResult({ id: ev.id, ok: true, value });",
        "    } catch (error) {",
        "      await postResult({ id: ev.id, ok: false, error: String(error?.message ?? error) });",
        "    }",
        "  };",
        "",
        "  const handleAction = async (ev) => {",
        "    const fn = actions[ev.name];",
        "    if (!fn) {",
        "      await postResult({ id: ev.id, ok: false, error: 'unknown action: ' + ev.name });",
        "      return;",
        "    }",
        "    try {",
        "      const value = await fn(ev.args ?? null, ev);",
        "      await postResult({ id: ev.id, ok: true, value });",
        "    } catch (error) {",
        "      await postResult({ id: ev.id, ok: false, error: String(error?.message ?? error) });",
        "    }",
        "  };",
        "",
        "  const applyEvent = (ev) => {",
        "    if (!ev || typeof ev !== 'object') return;",
        "    if (ev.type === 'ui.navigate' && typeof ev.path === 'string') {",
        "      window.location.assign(ev.path);",
        "      return;",
        "    }",
        "    if (ev.type === 'ui.notify') {",
        "      // Agent-scoped toasts belong to the tab showing that agent; the",
        "      // rail's unread badge is where other agents' activity shows.",
        "      const mine = document.body.dataset.agentId;",
        "      if (ev.agentId && mine && ev.agentId !== mine) return;",
        "      notify(ev);",
        "      return;",
        "    }",
        "    if (ev.type === 'secure-input.prompt' && typeof ev.id === 'string') {",
        "      secureInputRefresh();",,
        "      return;",
        "    }",
        "    if (ev.type === 'secure-input.prompt.closed' && typeof ev.id === 'string') {",
        "      secureInputRefresh();",
        "      return;",
        "    }",
        "    if (ev.type === 'ui.eval' && typeof ev.code === 'string' && typeof ev.id === 'string') {",
        "      void handleEval(ev);",
        "      return;",
        "    }",
        "    if (ev.type === 'ui.action' && typeof ev.name === 'string' && typeof ev.id === 'string') {",
        "      void handleAction(ev);",
        "    }",
        "    // screen.eval: the server pushes code down the stream; this tab runs",
        "    // it and answers at POST /screen/result. Each id runs once (the server",
        "    // re-sends into a connect gap); a tab without window.page keeps quiet;",
        "    // a hidden tab yields so the visible one answers first.",
        "    if (ev.type === 'eval' && typeof ev.id === 'number' && typeof ev.code === 'string') {",
        "      void (async () => {",
        "        if (evalRan.has(ev.id)) return;",
        "        evalRan.add(ev.id);",
        "        if (!window.page) return;",
        "        if (document.hidden) await new Promise(r => setTimeout(r, 400));",
        "        let body;",
        "        try {",
        "          const value = await new Function('return (async () => { ' + ev.code + ' })()')();",
        "          body = { id: ev.id, value: value === undefined ? null : value };",
        "        } catch (err) {",
        "          body = { id: ev.id, error: String(err) };",
        "        }",
        "        fetch('/screen/result', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });",
        "      })();",
        "      return;",
        "    }",
        "    // Chat freshness: a new event for the agent this tab shows fires",
        "    // 'hyper-tick' — the #msg-tail htmx trigger — so the transcript",
        "    // updates instantly instead of waiting for the 10s fallback poll.",
        "    if (ev.type === 'agent.event_appended' && ev.agentId === document.body.dataset.agentId) {",
        "      document.body.dispatchEvent(new Event('hyper-tick'));",
        "    }",
        "  };",
        "",
        "  window.__hyperUiApplyEvent = applyEvent;",
        "",
        "  // procs/events/client.js re-dispatches every SSE message as a",
        "  // 'hyper-events' DOM event — that is our transport now (the old build",
        "  // monkey-patched window.EventSource instead).",
        "  document.addEventListener('hyper-events', (e) => applyEvent(e.detail));",
        "  document.addEventListener('hyper-ui-event', (e) => applyEvent(e.detail));",
        "})();",
    ].join('\n');
}
