/** GET /knowledge — searchable Hyper-native overview of the typed knowledge graph. */
export default async function (ctx: Context, _session: Session | null, opts: { req: Request; params: Record<string, string> }) {
    const esc=(value:any)=>ctx.fns.procs.ui.escape({text:String(value??"")});
    const url=new URL(opts.req.url),query=(url.searchParams.get("q")??"").trim(),type=url.searchParams.get("type")??"";
    const [stats,types,hits]=await Promise.all([ctx.fns.knowledge.stats({}),ctx.fns.knowledge.types({}),query?ctx.fns.knowledge.find({query,type:type||undefined,limit:50}):Promise.resolve([])]);
    const cards=types.map((row:any)=>`<a href="/knowledge/${encodeURIComponent(row.type)}" class="group rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"><div class="flex items-center justify-between"><i class="ph ph-cube text-xl text-primary"></i><span class="text-2xl font-semibold tracking-tight">${row.count}</span></div><div class="mt-3 truncate text-sm font-medium group-hover:text-primary">${esc(row.type)}</div></a>`).join("");
    const results=hits.map((hit:any)=>`<a href="/knowledge/${hit.id.split('/').map(encodeURIComponent).join('/')}" class="block border-t border-base-200 px-4 py-3 first:border-t-0 hover:bg-base-200/50"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="truncate font-medium">${esc(hit.title??hit.id)}</div><p class="mt-1 line-clamp-2 text-xs leading-5 text-base-content/55">${esc(hit.summary??hit.snippet)}</p></div><span class="shrink-0 rounded-full border border-base-300 px-2 py-0.5 font-mono text-[10px] text-base-content/50">${esc(hit.type)}</span></div></a>`).join("");
    const main=`<div class="mx-auto w-full max-w-6xl p-5 sm:p-8"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-[.18em] text-primary"><i class="ph ph-graph"></i>Core plugin</div><h1 class="text-3xl font-semibold tracking-tight">Knowledge</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-base-content/55">Typed entities, sourced facts and relation graph in the isolated <code class="rounded bg-base-200 px-1.5 py-0.5">knowledge</code> schema.</p></div><div class="grid grid-cols-2 gap-2 text-center text-xs"><div class="rounded-lg border border-base-300 bg-base-100 px-4 py-2"><b class="block text-lg">${stats.entities}</b>entities</div><div class="rounded-lg border border-base-300 bg-base-100 px-4 py-2"><b class="block text-lg">${stats.relations}</b>relations</div></div></div>
<form class="mt-7 flex gap-2" method="get"><label class="relative flex-1"><i class="ph ph-magnifying-glass absolute left-3 top-1/2 -translate-y-1/2 text-base-content/35"></i><input name="q" value="${esc(query)}" placeholder="Search people, organizations, products and concepts" class="w-full rounded-xl border border-base-300 bg-base-100 py-3 pl-10 pr-4 text-sm shadow-sm outline-none focus:border-primary"></label>${type?`<input type="hidden" name="type" value="${esc(type)}">`:""}<button class="rounded-xl bg-primary px-5 text-sm font-medium text-primary-content hover:opacity-90">Search</button></form>
${query?`<section class="mt-6 overflow-hidden rounded-xl border border-base-300 bg-base-100 shadow-sm"><div class="flex items-center justify-between px-4 py-3"><h2 class="text-sm font-semibold">Results for “${esc(query)}”</h2><span class="text-xs text-base-content/45">${hits.length}</span></div>${results||`<div class="border-t border-base-200 p-8 text-center text-sm text-base-content/45">No matching entities</div>`}</section>`:`<section class="mt-8"><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-semibold">Entity types</h2><a href="/functions?namespace=knowledge" class="text-xs text-primary hover:underline">API documentation</a></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">${cards}</div></section>`}</div>`;
    return {title:"Knowledge",main};
}
