/**
 * Render a canonical entity with safe provenance backlinks, durable change history and relation details.
 * @param opts.req Incoming HTTP request.
 * @param opts.params Entity type and slug from the route.
 */
export default async function (ctx: Context, _session: Session | null, opts: { /** Incoming HTTP request. */ req: Request; /** Entity type and slug from the route. */ params: { type: string; slug: string } }) {
    const esc=(value:any)=>ctx.fns.procs.ui.escape({text:String(value??"")}),id=`${opts.params.type}/${opts.params.slug}`;
    const entity=await ctx.fns.knowledge.get({id}); if(!entity)return {status:404,main:"Knowledge entity not found"};
    const data=entity.data??{},skip=new Set(["title","summary","description","body"]);
    const value=(item:any):string=>{ if(Array.isArray(item))return item.map(value).join("<br>"); if(item&&typeof item==="object")return `<code class="whitespace-pre-wrap text-xs">${esc(JSON.stringify(item,null,2))}</code>`; const text=String(item??""); return /^[A-Za-z][\w-]*\/[\w.@-]+$/.test(text)?`<a class="text-primary hover:underline" href="/knowledge/${encodeURI(text)}">${esc(text)}</a>`:esc(text); };
    const facts=Object.entries(data).filter(([key,val])=>!skip.has(key)&&val!=null&&val!=="").map(([key,val])=>`<div class="grid gap-1 border-t border-base-200 py-3 first:border-t-0 sm:grid-cols-[10rem_1fr]"><dt class="font-mono text-[11px] text-base-content/45">${esc(key)}</dt><dd class="min-w-0 text-sm leading-6">${value(val)}</dd></div>`).join("");
    const sourceLink = (raw: string): string => {
        // Older observations used a nonfunctional scheme; render them through the real route.
        const legacy = /^hyper:\/\/agent\/([^/]+)\/message\/(\d+)$/.exec(raw);
        const url = legacy ? `/agent/${encodeURIComponent(legacy[1]!)}/message/${legacy[2]}` : raw;
        const chat = /^\/agent\/[^/?#]+\/message\/(\d+)$/.exec(url);
        const safe = Boolean(chat) || /^https?:\/\//i.test(url);
        return safe ? `<a href="${esc(url)}" class="mt-1 block break-all text-[11px] text-primary underline">${chat ? `Source chat · message ${chat[1]}` : esc(url)}</a>` : `<span class="mt-1 block text-[11px] text-base-content/50">${esc(raw)}</span>`;
    };
    const provenance=entity.provenance.map((item:any)=>{
        const observedValue=typeof item.value==="string"?item.value:JSON.stringify(item.value)??"—";
        return `<details class="group border-t border-base-200 first:border-t-0"><summary class="grid cursor-pointer grid-cols-2 items-start gap-x-3 gap-y-1 rounded px-2 py-2 text-xs hover:bg-base-200/50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,2fr)_minmax(0,0.8fr)]"><span class="min-w-0 break-words font-mono text-[11px]"><span aria-hidden="true" class="mr-1 inline-block transition-transform group-open:rotate-90">▸</span><span class="sr-only">Attribute: </span>${esc(item.attribute)}</span><span class="min-w-0 break-words text-base-content/60"><span class="sr-only">Source: </span>${esc(item.source)}</span><span class="min-w-0 truncate" title="${esc(observedValue)}"><span class="sr-only">Value: </span>${esc(observedValue)}</span><span class="min-w-0 break-words text-base-content/50"><span class="sr-only">Status: </span>${esc(item.status)}</span></summary><div class="mx-2 mb-3 space-y-2 border-l-2 border-base-300 pl-3 text-xs"><div><span class="font-medium">Value</span><p class="mt-1 whitespace-pre-wrap break-words text-base-content/70">${esc(observedValue)}</p></div>${item.evidence?`<div><span class="font-medium">Evidence</span><p class="mt-1 whitespace-pre-wrap break-words leading-5 text-base-content/60">${esc(item.evidence)}</p></div>`:""}${item.url?sourceLink(String(item.url)):""}${!item.evidence&&!item.url?`<p class="text-base-content/45">No evidence or source link recorded.</p>`:""}</div></details>`;
    }).join("");
    const backlinks = await ctx.fns.knowledge.renderBacklinks({ provenance: entity.provenance });
    const history = await ctx.fns.knowledge.renderHistory({ id });
    const edge=(label:string,target:string,dir:string)=>`<a href="/knowledge/${encodeURI(target)}" class="flex items-center gap-2 rounded-lg border border-base-300 px-3 py-2 text-xs hover:border-primary/40 hover:bg-primary/5"><i class="ph ${dir==='out'?'ph-arrow-right':'ph-arrow-left'} text-primary"></i><span class="font-mono text-base-content/45">${esc(label)}</span><span class="ml-auto truncate font-medium">${esc(target)}</span></a>`;
    const edges=[...entity.relations.outgoing.map((r:any)=>edge(r.predicate,r.object,"out")),...entity.relations.incoming.map((r:any)=>edge(r.predicate,r.subject,"in"))].join("");
    return {title:data.title??id,main:`<div class="mx-auto w-full max-w-7xl p-4 sm:p-6"><nav class="mb-5 flex items-center gap-2 text-xs text-base-content/45"><a href="/knowledge" class="hover:text-primary">Knowledge</a><i class="ph ph-caret-right"></i><a href="/knowledge/${encodeURIComponent(entity.type)}" class="hover:text-primary">${esc(entity.type)}</a><i class="ph ph-caret-right"></i><span class="truncate">${esc(opts.params.slug)}</span></nav><header class="rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm"><div class="flex items-start gap-4"><div class="flex size-12 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-2xl text-primary"><i class="ph ph-node"></i></div><div class="min-w-0"><div class="font-mono text-[10px] uppercase tracking-widest text-primary">${esc(entity.type)}</div><h1 class="mt-1 truncate text-2xl font-semibold tracking-tight">${esc(data.title??opts.params.slug)}</h1>${data.summary?`<p class="mt-2 text-sm text-base-content/60">${esc(data.summary)}</p>`:""}${data.description?`<p class="mt-3 max-w-3xl text-sm leading-6 text-base-content/55">${esc(data.description)}</p>`:""}</div></div></header><div class="mt-5 grid gap-5 lg:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]"><div class="min-w-0 space-y-5"><section class="rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-2 text-sm font-semibold">Canonical facts</h2><dl>${facts||`<div class="py-4 text-sm text-base-content/40">No additional facts</div>`}</dl></section>${data.body?`<section class="rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-3 text-sm font-semibold">Notes</h2><div class="whitespace-pre-wrap text-sm leading-6 text-base-content/65">${esc(data.body)}</div></section>`:""}</div><aside class="min-w-0 space-y-5">${backlinks.html}<section class="rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-3 text-sm font-semibold">Relations <span class="font-normal text-base-content/40">${entity.relations.outgoing.length+entity.relations.incoming.length}</span></h2><div class="space-y-2">${edges||`<p class="text-xs text-base-content/40">No relations</p>`}</div></section></aside>${history.html}<section class="min-w-0 rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm lg:col-span-2"><h2 class="mb-2 text-sm font-semibold">Provenance <span class="font-normal text-base-content/40">${entity.provenance.length}</span></h2><p class="mb-3 text-xs text-base-content/50">Expand a row for evidence and source link.</p><div aria-hidden="true" class="hidden grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,2fr)_minmax(0,0.8fr)] gap-3 border-b border-base-200 px-2 pb-2 text-[10px] font-medium uppercase tracking-wide text-base-content/45 sm:grid"><span>Attribute</span><span>Source</span><span>Value</span><span>Status</span></div>${provenance||`<p class="py-2 text-xs text-base-content/40">No observations</p>`}</section></div></div>`};
}
