/** GET /knowledge/:type/:slug — canonical entity, provenance and relation graph detail. */
export default async function (ctx: Context, _session: Session | null, opts: { req: Request; params: { type: string; slug: string } }) {
    const esc=(value:any)=>ctx.fns.procs.ui.escape({text:String(value??"")}),id=`${opts.params.type}/${opts.params.slug}`;
    const entity=await ctx.fns.knowledge.get({id}); if(!entity)return {status:404,main:"Knowledge entity not found"};
    const data=entity.data??{},skip=new Set(["title","summary","description","body"]);
    const value=(item:any):string=>{ if(Array.isArray(item))return item.map(value).join("<br>"); if(item&&typeof item==="object")return `<code class="whitespace-pre-wrap text-xs">${esc(JSON.stringify(item,null,2))}</code>`; const text=String(item??""); return /^[A-Za-z][\w-]*\/[\w.@-]+$/.test(text)?`<a class="text-primary hover:underline" href="/knowledge/${encodeURI(text)}">${esc(text)}</a>`:esc(text); };
    const facts=Object.entries(data).filter(([key,val])=>!skip.has(key)&&val!=null&&val!=="").map(([key,val])=>`<div class="grid gap-1 border-t border-base-200 py-3 first:border-t-0 sm:grid-cols-[10rem_1fr]"><dt class="font-mono text-[11px] text-base-content/45">${esc(key)}</dt><dd class="min-w-0 text-sm leading-6">${value(val)}</dd></div>`).join("");
    const provenance=entity.provenance.map((item:any)=>`<div class="border-t border-base-200 py-3 first:border-t-0"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border border-base-300 px-2 py-0.5 font-mono text-[10px]">${esc(item.attribute)}</span><span class="text-xs font-medium">${esc(item.source)}</span><span class="ml-auto text-[10px] text-base-content/35">${esc(item.status)}</span></div>${item.evidence?`<p class="mt-2 text-xs leading-5 text-base-content/60">${esc(item.evidence)}</p>`:""}${item.url?`<a href="${esc(item.url)}" class="mt-1 block truncate text-[11px] text-primary hover:underline">${esc(item.url)}</a>`:""}</div>`).join("");
    const edge=(label:string,target:string,dir:string)=>`<a href="/knowledge/${encodeURI(target)}" class="flex items-center gap-2 rounded-lg border border-base-300 px-3 py-2 text-xs hover:border-primary/40 hover:bg-primary/5"><i class="ph ${dir==='out'?'ph-arrow-right':'ph-arrow-left'} text-primary"></i><span class="font-mono text-base-content/45">${esc(label)}</span><span class="ml-auto truncate font-medium">${esc(target)}</span></a>`;
    const edges=[...entity.relations.outgoing.map((r:any)=>edge(r.predicate,r.object,"out")),...entity.relations.incoming.map((r:any)=>edge(r.predicate,r.subject,"in"))].join("");
    return {title:data.title??id,main:`<div class="mx-auto w-full max-w-5xl p-5 sm:p-8"><nav class="mb-5 flex items-center gap-2 text-xs text-base-content/45"><a href="/knowledge" class="hover:text-primary">Knowledge</a><i class="ph ph-caret-right"></i><a href="/knowledge/${encodeURIComponent(entity.type)}" class="hover:text-primary">${esc(entity.type)}</a><i class="ph ph-caret-right"></i><span class="truncate">${esc(opts.params.slug)}</span></nav><header class="rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm"><div class="flex items-start gap-4"><div class="flex size-12 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-2xl text-primary"><i class="ph ph-node"></i></div><div class="min-w-0"><div class="font-mono text-[10px] uppercase tracking-widest text-primary">${esc(entity.type)}</div><h1 class="mt-1 truncate text-2xl font-semibold tracking-tight">${esc(data.title??opts.params.slug)}</h1>${data.summary?`<p class="mt-2 text-sm text-base-content/60">${esc(data.summary)}</p>`:""}${data.description?`<p class="mt-3 max-w-3xl text-sm leading-6 text-base-content/55">${esc(data.description)}</p>`:""}</div></div></header><div class="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]"><div class="space-y-5"><section class="rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-2 text-sm font-semibold">Canonical facts</h2><dl>${facts||`<div class="py-4 text-sm text-base-content/40">No additional facts</div>`}</dl></section>${data.body?`<section class="rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-3 text-sm font-semibold">Notes</h2><div class="whitespace-pre-wrap text-sm leading-6 text-base-content/65">${esc(data.body)}</div></section>`:""}</div><aside class="space-y-5"><section class="rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-3 text-sm font-semibold">Relations <span class="font-normal text-base-content/40">${entity.relations.outgoing.length+entity.relations.incoming.length}</span></h2><div class="space-y-2">${edges||`<p class="text-xs text-base-content/40">No relations</p>`}</div></section><section class="rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-2 text-sm font-semibold">Provenance <span class="font-normal text-base-content/40">${entity.provenance.length}</span></h2>${provenance||`<p class="py-2 text-xs text-base-content/40">No observations</p>`}</section></aside></div></div>`};
}
