import{createHash}from"node:crypto";
/** Incrementally synchronizes one configured Hacker News feed and publishes new or changed stories to News. */
export default async function(ctx:Context,_session:Session|null,opts:{
 /** Configured feed key. */ feed:string;
 /** Maximum Algolia hits requested. @default 100 @minimum 1 @maximum 1000 */ limit?:number;
}):Promise<{feed:string;fetched:number;added:number;updated:number;unchanged:number;published:number}>{
 const feed=(await ctx.fns.procs.db.select({sql:"SELECT * FROM hackernews.feeds WHERE key=?",params:[opts.feed]}))[0];if(!feed)throw new Error(`hackernews.sync: unknown feed ${opts.feed}`);const run=(await ctx.fns.procs.db.select({sql:"INSERT INTO hackernews.runs(feed_key) VALUES(?) RETURNING id",params:[feed.key]}))[0],limit=Math.max(1,Math.min(1000,opts.limit??feed.fetch_limit??100));
 try{let hits:any[]=[];if(feed.mode==="front"){const since=Math.floor(Date.now()/1000)-86400,p=new URLSearchParams({tags:"story",numericFilters:`created_at_i>${since}`,hitsPerPage:"100"}),response=await fetch(`https://hn.algolia.com/api/v1/search?${p}`);if(!response.ok)throw new Error(`HTTP ${response.status}`);hits=(((await response.json())as any).hits??[]).sort((a:any,b:any)=>(b.points??0)-(a.points??0)||(b.num_comments??0)-(a.num_comments??0)).slice(0,limit)}else{const queries:Array<string>=feed.queries?.length?feed.queries:[feed.query],seen=new Map<string,any>();for(const query of queries){const p=new URLSearchParams({query,tags:"story",hitsPerPage:String(limit),...(feed.title_only?{restrictSearchableAttributes:"title"}:{}),...(feed.typo_tolerance===false?{typoTolerance:"false"}:{})}),response=await fetch(`https://hn.algolia.com/api/v1/${feed.mode==="top"?"search":"search_by_date"}?${p}`);if(!response.ok)throw new Error(`HTTP ${response.status} for ${query}`);for(const hit of ((await response.json())as any).hits??[])if(!seen.has(String(hit.objectID)))seen.set(String(hit.objectID),hit)}hits=[...seen.values()].sort((a:any,b:any)=>Date.parse(b.created_at??0)-Date.parse(a.created_at??0))}let added=0,updated=0,unchanged=0,published=0;
  for(let rank=0;rank<hits.length;rank++){const h=hits[rank],id=String(h.objectID),payload={id,title:h.title??h.story_title??"Untitled",url:h.url??h.story_url??`https://news.ycombinator.com/item?id=${id}`,author:h.author??null,createdAt:h.created_at??null,points:h.points??0,comments:h.num_comments??0,storyText:h.story_text??null},hash=createHash("sha256").update(JSON.stringify(payload)).digest("hex"),old=(await ctx.fns.procs.db.select({sql:"SELECT content_hash,news_id FROM hackernews.stories WHERE id=?",params:[id]}))[0],changed=!old||old.content_hash!==hash||!old.news_id;if(!old)added++;else if(changed)updated++;else unchanged++;await ctx.fns.procs.db.run({sql:`INSERT INTO hackernews.stories(id,title,url,author,created_at,points,comments,story_text,content_hash,last_seen_at,raw) VALUES(?,?,?,?,?::timestamptz,?,?,?,?,now(),?::jsonb) ON CONFLICT(id) DO UPDATE SET title=excluded.title,url=excluded.url,author=excluded.author,created_at=excluded.created_at,points=excluded.points,comments=excluded.comments,story_text=excluded.story_text,content_hash=excluded.content_hash,last_seen_at=now(),raw=excluded.raw`,params:[id,payload.title,payload.url,payload.author,payload.createdAt,payload.points,payload.comments,payload.storyText,hash,JSON.stringify(h)]});await ctx.fns.procs.db.run({sql:`INSERT INTO hackernews.feed_stories(feed_key,story_id,rank,matched_at) VALUES(?,?,?,now()) ON CONFLICT(feed_key,story_id) DO UPDATE SET rank=excluded.rank,matched_at=now()`,params:[feed.key,id,rank+1]});if(changed){const newsId=old?.news_id??`hn:${id}`,source=feed.key==="front"?"hn":`hn-${feed.key}`;await ctx.fns.news.put({id:newsId,title:payload.title,source,sourceLabel:feed.label,url:payload.url,author:payload.author??undefined,points:payload.points,comments:payload.comments,summary:payload.storyText??payload.title,articleMarkdown:payload.storyText??undefined,shownAt:payload.createdAt??undefined,query:feed.query||undefined});await ctx.fns.procs.db.run({sql:"UPDATE hackernews.stories SET news_id=? WHERE id=?",params:[newsId,id]});try{await ctx.fns.news.summarize({id:newsId,force:!!old})}catch(error:any){ctx.fns.procs.log.warn({event:"hackernews.sync.summarize",feed:feed.key,newsId,msg:String(error?.message??error)})}published++}}
  const cursor={syncedAt:new Date().toISOString(),lastStoryId:hits[0]?.objectID??feed.cursor?.lastStoryId,query:feed.query,mode:feed.mode};await ctx.fns.procs.db.run({sql:"UPDATE hackernews.feeds SET cursor=?::jsonb,last_sync_at=now(),last_error=NULL WHERE key=?",params:[JSON.stringify(cursor),feed.key]});await ctx.fns.procs.db.run({sql:"UPDATE hackernews.runs SET finished_at=now(),fetched=?,added=?,updated=?,unchanged=? WHERE id=?",params:[hits.length,added,updated,unchanged,run.id]});return{feed:feed.key,fetched:hits.length,added,updated,unchanged,published}
 }catch(error:any){await ctx.fns.procs.db.run({sql:"UPDATE hackernews.feeds SET last_sync_at=now(),last_error=? WHERE key=?",params:[String(error?.message??error),feed.key]});await ctx.fns.procs.db.run({sql:"UPDATE hackernews.runs SET finished_at=now(),error=? WHERE id=?",params:[String(error?.message??error),run.id]});throw error}
}
