/** Renders the neutral Hyper landing page for first-run setup and returning users. */
export default async function (ctx: Context, _session: Session | null, _opts?: {}): Promise<{ title: string; main: string }> {
    const esc = (value: any) => ctx.fns.procs.ui.escape({ text: String(value ?? "") });
    const [agents, accounts] = await Promise.all([
        ctx.fns.session.list({}),
        ctx.fns.llm.listAccounts({}).catch(() => [] as any[]),
    ]);
    const running = agents.filter((item: any) => item.runState !== "idle");
    const recent = agents.slice(0, 10);
    const connected = accounts.filter((item: any) => item.available !== false);
    const card = (title: string, body: string, href: string, action: string, done: boolean) => `<a href="${href}" class="rounded-xl border ${done ? "border-emerald-200 bg-emerald-50/60" : "border-ui-border bg-base-100"} p-4 shadow-sm hover:border-primary/40"><div class="flex items-center gap-2 text-sm font-semibold"><i class="ph ${done ? "ph-check-circle text-emerald-600" : "ph-circle text-base-content/30"}"></i>${title}</div><p class="mt-2 text-xs text-base-content/55">${body}</p><div class="mt-3 text-xs font-medium text-primary">${action} →</div></a>`;
    const agentRows = recent.map((item: any) => `<a href="/agent/${encodeURIComponent(item.id)}" class="flex items-center gap-2 rounded-lg px-3 py-2 hover:bg-base-200"><span class="size-2 rounded-full ${item.runState === "idle" ? "bg-base-content/20" : "bg-emerald-500"}"></span><span class="min-w-0 flex-1 truncate text-sm">${esc(item.title || item.id)}</span><span class="font-mono text-[10px] text-base-content/40">${esc(item.id)}</span>${item.unread ? `<span class="rounded-full bg-emerald-500 px-1.5 text-[10px] text-white">${item.unread}</span>` : ""}</a>`).join("");
    return { title: "Home", main: `<main class="min-h-full flex-1 overflow-y-auto bg-base-200 p-6"><div class="mx-auto max-w-5xl space-y-6"><header><h1 class="text-2xl font-semibold">Hyper</h1><p class="mt-1 text-sm text-base-content/55">A programmable workspace for durable agents.</p></header><section class="grid gap-3 md:grid-cols-3">${card("Connect an LLM", connected.length ? `${connected.length} account${connected.length === 1 ? "" : "s"} available` : "Connect Claude, Codex or another provider first.", "/llms", connected.length ? "Manage connections" : "Connect account", connected.length > 0)}${card("Create an agent", agents.length ? `${agents.length} agent${agents.length === 1 ? "" : "s"} created` : "Choose a model and workspace to start.", "/agent/new", "New agent", agents.length > 0)}${card("Open workspace files", agents[0]?.workspaceDir ? esc(agents[0].workspaceDir) : "Browse the current project and documentation.", "/files", "Open Files", !!agents[0]?.workspaceDir)}</section>${running.length ? `<section class="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4"><h2 class="text-xs font-semibold uppercase tracking-wider text-emerald-700">Running now</h2><div class="mt-2 flex flex-wrap gap-2">${running.map((item: any) => `<a href="/agent/${encodeURIComponent(item.id)}" class="rounded-lg bg-base-100 px-3 py-2 text-sm shadow-sm hover:text-primary">${esc(item.title || item.id)}</a>`).join("")}</div></section>` : ""}<section class="rounded-xl border border-ui-border bg-base-100 p-3 shadow-sm"><div class="flex items-center justify-between px-2 py-1"><h2 class="text-xs font-semibold uppercase tracking-wider text-base-content/50">Recent agents</h2>${agents[0] ? `<a href="/agent/${encodeURIComponent(agents[0].id)}" class="text-xs text-primary">Resume latest</a>` : ""}</div><div class="mt-1">${agentRows || `<div class="px-3 py-8 text-center text-sm text-base-content/40">No agents yet. Connect a model, then create your first agent.</div>`}</div></section></div></main>` };
}
