import{createHash}from"node:crypto";
/** Strictly synchronizes one Substack publication and publishes new or changed posts to News with URL deduplication. */
export default async function(ctx:Context,_session:Session|null,opts:{
 /** Stable publication key. */ key:string;
 /** Maximum recent archive posts inspected. @default 30 @minimum 1 @maximum 500 */ max?:number;
 /** Browser session name. @default substack */ session?:string;
}):Promise<{key:string;fetched:number;added:number;updated:number;unchanged:number;published:number}>{
 await ctx.fns.procs.migrate.up({});const pub=(await ctx.fns.procs.db.select({sql:"SELECT * FROM substack.publications WHERE key=?",params:[opts.key]}))[0];if(!pub)throw new Error(`substack.sync: unknown publication ${opts.key}`);const run=(await ctx.fns.procs.db.select({sql:"INSERT INTO substack.runs(publication_key) VALUES(?) RETURNING id",params:[pub.key]}))[0];
 try{const metas=await ctx.fns.substack.archive({host:pub.host,max:opts.max,session:opts.session});let added=0,updated=0,unchanged=0,published=0;for(const meta of metas){let old=(await ctx.fns.procs.db.select({sql:"SELECT id,content_hash,news_id FROM substack.posts WHERE publication_key=? AND (slug=? OR external_id=?) LIMIT 1",params:[pub.key,meta.slug,String(meta.id)]}))[0];if(old?.content_hash&&old.news_id){unchanged++;await ctx.fns.procs.db.run({sql:"UPDATE substack.posts SET last_seen_at=now() WHERE id=?",params:[old.id]});continue}const post=await ctx.fns.substack.post({host:pub.host,slug:meta.slug,session:opts.session}),hash=createHash("sha256").update(JSON.stringify({...meta,markdown:post.markdown})).digest("hex"),changed=!old||old.content_hash!==hash||!old.news_id;if(!old)added++;else if(changed)updated++;else unchanged++;await ctx.fns.procs.db.run({sql:`INSERT INTO substack.posts(id,publication_key,external_id,slug,title,subtitle,url,audience,published_at,reactions,comments,body_markdown,body_length,content_hash,last_seen_at,raw) VALUES(?,?,?,?,?,?,?,?,?::timestamptz,?,?,?,?,?,now(),?::jsonb) ON CONFLICT(publication_key,slug) DO UPDATE SET external_id=coalesce(excluded.external_id,substack.posts.external_id),title=excluded.title,subtitle=excluded.subtitle,url=excluded.url,audience=excluded.audience,published_at=excluded.published_at,reactions=excluded.reactions,comments=excluded.comments,body_markdown=excluded.body_markdown,body_length=excluded.body_length,content_hash=excluded.content_hash,last_seen_at=now(),raw=excluded.raw`,params:[meta.id,pub.key,String(meta.id),meta.slug,meta.title,meta.subtitle,post.url??meta.url,meta.audience,meta.date,meta.reactions,meta.comments,post.markdown,post.bodyLength,hash,JSON.stringify(meta)]});if(changed){const url=post.url??meta.url;const duplicate=url?(await ctx.fns.procs.db.select({sql:`SELECT id FROM news.items WHERE url IS NOT NULL AND lower(regexp_replace(regexp_replace(url,'^https?://(www\\.)?','','i'),'/+$',''))=lower(regexp_replace(regexp_replace(?::text,'^https?://(www\\.)?','','i'),'/+$','')) ORDER BY (source=?) DESC LIMIT 1`,params:[url,pub.key]}))[0]:null,newsId=old?.news_id??duplicate?.id??`substack:${pub.key}:${meta.id}`;await ctx.fns.news.put({id:newsId,title:meta.title,source:pub.key,sourceLabel:pub.name,url,summary:meta.subtitle??post.markdown,articleMarkdown:post.markdown,shownAt:meta.date,points:meta.reactions,comments:meta.comments});await ctx.fns.procs.db.run({sql:"UPDATE substack.posts SET news_id=? WHERE publication_key=? AND slug=?",params:[newsId,pub.key,meta.slug]});try{await ctx.fns.news.summarize({id:newsId,force:!!old||!!duplicate})}catch(error:any){ctx.fns.procs.log.warn({event:"substack.sync.summarize",key:pub.key,newsId,msg:String(error?.message??error)})}published++}}
  const cursor={lastPostId:metas[0]?.id??pub.cursor?.lastPostId,lastPublishedAt:metas[0]?.date??pub.cursor?.lastPublishedAt,syncedAt:new Date().toISOString()};await ctx.fns.procs.db.run({sql:"UPDATE substack.publications SET cursor=?::jsonb,last_sync_at=now(),last_error=NULL WHERE key=?",params:[JSON.stringify(cursor),pub.key]});await ctx.fns.procs.db.run({sql:"UPDATE substack.runs SET finished_at=now(),fetched=?,added=?,updated=?,unchanged=? WHERE id=?",params:[metas.length,added,updated,unchanged,run.id]});return{key:pub.key,fetched:metas.length,added,updated,unchanged,published}
 }catch(error:any){await ctx.fns.procs.db.run({sql:"UPDATE substack.publications SET last_sync_at=now(),last_error=? WHERE key=?",params:[String(error?.message??error),pub.key]});await ctx.fns.procs.db.run({sql:"UPDATE substack.runs SET finished_at=now(),error=? WHERE id=?",params:[String(error?.message??error),run.id]});throw error}
}
