/** Strictly incrementally loads one feed and publishes only new or changed entries through `news.put`. */
export default async function(ctx:Context,_session:Session|null,opts:{
 /** Stable feed key. */ key:string;
 /** Maximum newest entries inspected. @default 30 @minimum 1 @maximum 200 */ limit?:number;
 /** Store entry state without publishing changes to News. @default false */ dryRun?:boolean;
}):Promise<{key:string;fetched:number;added:number;updated:number;unchanged:number;published:number;notModified:boolean}>{
 await ctx.fns.rss.ensure({});const feed=(await ctx.fns.procs.db.select({sql:"SELECT * FROM rss.feeds WHERE key=?",params:[opts.key]}))[0];if(!feed)throw new Error(`rss.load: unknown feed ${opts.key}`);const run=(await ctx.fns.procs.db.select({sql:"INSERT INTO rss.runs(feed_key) VALUES(?) RETURNING id",params:[opts.key]}))[0];
 try{const cursor=feed.cursor??{},headers:Record<string,string>={accept:"application/rss+xml,application/atom+xml,application/xml,text/xml","user-agent":"hyper-rss/1.0"};const etag=cursor.etag??feed.etag,lastModified=cursor.lastModified??feed.last_modified;if(etag)headers["if-none-match"]=etag;if(lastModified)headers["if-modified-since"]=lastModified;const response=await fetch(feed.url,{headers});if(response.status===304){await finish(ctx,run.id,opts.key,"ok",{fetched:0,added:0,updated:0,unchanged:0,published:0},null,response,cursor);return {key:opts.key,fetched:0,added:0,updated:0,unchanged:0,published:0,notModified:true}}if(!response.ok)throw new Error(`HTTP ${response.status}`);const items=ctx.fns.rss.parse({xml:await response.text()}).slice(0,Math.max(1,Math.min(200,opts.limit??30)));let added=0,updated=0,unchanged=0,published=0,newest:any=null;
 for(const item of items){const hash=ctx.fns.rss.hash(item),old=(await ctx.fns.procs.db.select({sql:"SELECT content_hash,news_id FROM rss.entries WHERE feed_key=? AND external_id=?",params:[opts.key,item.id]}))[0];const changed=!old||old.content_hash!==hash;if(!old)added++;else if(changed)updated++;else unchanged++;await ctx.fns.procs.db.run({sql:`INSERT INTO rss.entries(feed_key,external_id,title,url,author,published_at,description,content,payload,content_hash,last_seen_at) VALUES(?,?,?,?,?,?::timestamptz,?,?,?::jsonb,?,now()) ON CONFLICT(feed_key,external_id) DO UPDATE SET title=excluded.title,url=excluded.url,author=excluded.author,published_at=excluded.published_at,description=excluded.description,content=excluded.content,payload=excluded.payload,content_hash=excluded.content_hash,last_seen_at=now()`,params:[opts.key,item.id,item.title,item.url,item.author??null,item.publishedAt??null,item.description??null,item.content??null,JSON.stringify(item),hash]});if(changed&&!opts.dryRun){const newsId=old?.news_id??`rss:${opts.key}:${item.id}`;await ctx.fns.news.put({id:newsId,title:item.title,source:opts.key,url:item.url,author:item.author,summary:item.description??item.content,articleMarkdown:item.content,shownAt:item.publishedAt});await ctx.fns.procs.db.run({sql:"UPDATE rss.entries SET news_id=? WHERE feed_key=? AND external_id=?",params:[newsId,opts.key,item.id]});published++;}if(item.publishedAt&&(!newest||item.publishedAt>newest.publishedAt))newest={publishedAt:item.publishedAt,id:item.id};}
 const nextCursor={...cursor,etag:response.headers.get("etag")??etag??undefined,lastModified:response.headers.get("last-modified")??lastModified??undefined,newestPublishedAt:newest?.publishedAt??cursor.newestPublishedAt,newestExternalId:newest?.id??cursor.newestExternalId};const counts={fetched:items.length,added,updated,unchanged,published};await finish(ctx,run.id,opts.key,"ok",counts,null,response,nextCursor);return {key:opts.key,...counts,notModified:false};}catch(error:any){await finish(ctx,run.id,opts.key,"error",{fetched:0,added:0,updated:0,unchanged:0,published:0},String(error?.message??error),undefined,feed.cursor??{});throw error;}
}
async function finish(ctx:Context,id:number,key:string,status:string,c:{fetched:number;added:number;updated:number;unchanged:number;published:number},error:string|null,response:Response|undefined,cursor:any){await ctx.fns.procs.db.run({sql:"UPDATE rss.runs SET finished_at=now(),status=?,fetched=?,added=?,updated=?,unchanged=?,published=?,error=? WHERE id=?",params:[status,c.fetched,c.added,c.updated,c.unchanged,c.published,error,id]});await ctx.fns.procs.db.run({sql:`UPDATE rss.feeds SET last_loaded_at=now(),last_success_at=${status==="ok"?"now()":"last_success_at"},last_error=?,etag=coalesce(?,etag),last_modified=coalesce(?,last_modified),cursor=?::jsonb,updated_at=now() WHERE key=?`,params:[error,response?.headers.get("etag")??null,response?.headers.get("last-modified")??null,JSON.stringify(cursor??{}),key]});}
