/** Incrementally imports one configured Telegram channel into News verbatim, including publicly hosted photos and no LLM summarization. */
export default async function(ctx:Context,_session:Session|null,opts:{
 /** Telegram channel peer identifier. */ chat:string|number;
 /** Maximum recent messages inspected. @default 50 @minimum 1 @maximum 500 */ max?:number;
}):Promise<{chatId:string;fetched:number;added:number;updated:number;unchanged:number;published:number;cursor:Record<string,any>}>{
 await ctx.fns.procs.migrate.up({});const chatId=String(opts.chat),channel=(await ctx.fns.procs.db.select({sql:"SELECT * FROM telegram.news_channels WHERE chat_id=?",params:[chatId]}))[0];if(!channel)throw new Error(`telegram.newsSyncChannel: unknown channel ${chatId}`);
 try{const messages=await ctx.fns.telegram.messages({chat:chatId,max:Math.max(1,Math.min(500,opts.max??50))});let added=0,updated=0,unchanged=0,published=0,maxMessageId=Number(channel.cursor?.maxMessageId??0),newestDate=channel.cursor?.newestDate??null;for(const message of messages){const id=Number(message.id);if(!Number.isFinite(id))continue;let text=String(message.text??"").trim();const mediaOnly=!text||text==="[media/no text]";if(mediaOnly&&!message.hasPhoto)continue;if(mediaOnly)text="";const newsId=`tg:${chatId}:${id}`,existingNews=await ctx.fns.news.get({id:newsId}),needsImage=!!message.hasPhoto&&!existingNews?.image_url,hash=ctx.fns.telegram.newsHash({chat:chatId,id,text,hasPhoto:message.hasPhoto,date:message.date}),old=(await ctx.fns.procs.db.select({sql:"SELECT content_hash,news_id FROM telegram.news_posts WHERE chat_id=? AND message_id=?",params:[chatId,id]}))[0],changed=!old||old.content_hash!==hash||!old.news_id||needsImage;if(!old)added++;else if(changed)updated++;else unchanged++;if(changed){let imageUrl:string|undefined;if(message.hasPhoto)try{imageUrl=await ctx.fns.telegram.photoPublic({chat:chatId,id})??undefined}catch(error:any){ctx.fns.procs.log.warn({event:"telegram.newsSyncChannel.photo",chatId,id,msg:String(error?.message??error)})}if(!text&&!imageUrl)continue;const date=message.date==null?undefined:new Date(typeof message.date==="number"?message.date*1000:message.date).toISOString(),internal=chatId.replace(/^-100/,"");await ctx.fns.news.put({id:newsId,title:channel.title,source:"telegram",sourceLabel:channel.title,url:`https://t.me/c/${internal}/${id}`,imageUrl,author:channel.title,summary:text,shownAt:date});await ctx.fns.procs.db.run({sql:`INSERT INTO telegram.news_posts(chat_id,message_id,content_hash,news_id,message_date,last_seen_at) VALUES(?,?,?,?,?::timestamptz,now()) ON CONFLICT(chat_id,message_id) DO UPDATE SET content_hash=excluded.content_hash,news_id=excluded.news_id,message_date=excluded.message_date,last_seen_at=now()`,params:[chatId,id,hash,newsId,date??null]});published++}else await ctx.fns.procs.db.run({sql:"UPDATE telegram.news_posts SET last_seen_at=now() WHERE chat_id=? AND message_id=?",params:[chatId,id]});if(id>maxMessageId)maxMessageId=id;if(message.date){const iso=new Date(typeof message.date==="number"?message.date*1000:message.date).toISOString();if(!newestDate||iso>newestDate)newestDate=iso}}
  const cursor={...(channel.cursor??{}),maxMessageId,newestDate};await ctx.fns.procs.db.run({sql:"UPDATE telegram.news_channels SET cursor=?::jsonb,last_sync_at=now(),last_success_at=now(),last_error=NULL,updated_at=now() WHERE chat_id=?",params:[JSON.stringify(cursor),chatId]});return{chatId,fetched:messages.length,added,updated,unchanged,published,cursor}
 }catch(error:any){await ctx.fns.procs.db.run({sql:"UPDATE telegram.news_channels SET last_sync_at=now(),last_error=?,updated_at=now() WHERE chat_id=?",params:[String(error?.message??error),chatId]});throw error}
}
