// Auto-generated by ctx.genTypes — do not edit
// Injected<F> strips (ctx, session) — they are injected by the ctx.fns Proxy.
type Injected<F> = F extends (ctx: any, session: any, ...args: infer A) => infer R ? (...args: A) => R : never;

declare global {
    type Context = import("./Context").Context;

    interface FnsRegistry {
        agent: {
            buildDelegatedTaskPrompt: Injected<typeof import("./agent/buildDelegatedTaskPrompt").default>;
            buildLlmRequest: Injected<typeof import("./agent/buildLlmRequest").default>;
            clear: Injected<typeof import("./agent/clear").default>;
            compact: Injected<typeof import("./agent/compact").default>;
            delegateTask: Injected<typeof import("./agent/delegateTask").default>;
            executeBash: Injected<typeof import("./agent/executeBash").default>;
            executeMarker: Injected<typeof import("./agent/executeMarker").default>;
            finishTask: Injected<typeof import("./agent/finishTask").default>;
            formatMarkerError: Injected<typeof import("./agent/formatMarkerError").default>;
            formatMarkerResult: Injected<typeof import("./agent/formatMarkerResult").default>;
            fullSystemPrompt: Injected<typeof import("./agent/fullSystemPrompt").default>;
            getBasePromptParts: Injected<typeof import("./agent/getBasePromptParts").default>;
            highlightResult: Injected<typeof import("./agent/highlightResult").default>;
            listPromptPresets: Injected<typeof import("./agent/listPromptPresets").default>;
            llmCall: Injected<typeof import("./agent/llmCall").default>;
            markerKind: Injected<typeof import("./agent/markerKind").default>;
            nextId: Injected<typeof import("./agent/nextId").default>;
            parseMarkers: Injected<typeof import("./agent/parseMarkers").default>;
            parseReadMarker: Injected<typeof import("./agent/parseReadMarker").default>;
            preflightCall: Injected<typeof import("./agent/preflightCall").default>;
            readAndSummarize: Injected<typeof import("./agent/readAndSummarize").default>;
            renderEventHtml: Injected<typeof import("./agent/renderEventHtml").default>;
            renderEventsHtml: Injected<typeof import("./agent/renderEventsHtml").default>;
            renderStatusBar: Injected<typeof import("./agent/renderStatusBar").default>;
            run: Injected<typeof import("./agent/run").default>;
            sanitizeHtmlBody: Injected<typeof import("./agent/sanitizeHtmlBody").default>;
            serializeMarkerCall: Injected<typeof import("./agent/serializeMarkerCall").default>;
            start: Injected<typeof import("./agent/start").default>;
            stashResult: Injected<typeof import("./agent/stashResult").default>;
            stop: Injected<typeof import("./agent/stop").default>;
            waitForEvent: Injected<typeof import("./agent/waitForEvent").default>;
            wakeWaiters: Injected<typeof import("./agent/wakeWaiters").default>;
            wakeWorker: Injected<typeof import("./agent/wakeWorker").default>;
            workerLoop: Injected<typeof import("./agent/workerLoop").default>;
        };
        dev: {
            ping: Injected<typeof import("./dev/ping").default>;
            readLog: Injected<typeof import("./dev/readLog").default>;
            test: Injected<typeof import("./dev/test").default>;
            testSummary: Injected<typeof import("./dev/testSummary").default>;
            typecheck: Injected<typeof import("./dev/typecheck").default>;
        };
        events: {
            emitAgentsChanged: Injected<typeof import("./events/emitAgentsChanged").default>;
        };
        files: {
            close: Injected<typeof import("./files/close").default>;
            editHashline: Injected<typeof import("./files/editHashline").default>;
            exists: Injected<typeof import("./files/exists").default>;
            formatHashline: Injected<typeof import("./files/formatHashline").default>;
            grep: Injected<typeof import("./files/grep").default>;
            grepHashline: Injected<typeof import("./files/grepHashline").default>;
            lineHash: Injected<typeof import("./files/lineHash").default>;
            list: Injected<typeof import("./files/list").default>;
            listOpen: Injected<typeof import("./files/listOpen").default>;
            mkdir: Injected<typeof import("./files/mkdir").default>;
            open: Injected<typeof import("./files/open").default>;
            parseAnchor: Injected<typeof import("./files/parseAnchor").default>;
            parseHashlineEdit: Injected<typeof import("./files/parseHashlineEdit").default>;
            read: Injected<typeof import("./files/read").default>;
            readHashline: Injected<typeof import("./files/readHashline").default>;
            remove: Injected<typeof import("./files/remove").default>;
            rename: Injected<typeof import("./files/rename").default>;
            resolveSafe: Injected<typeof import("./files/resolveSafe").default>;
            stat: Injected<typeof import("./files/stat").default>;
            write: Injected<typeof import("./files/write").default>;
        };
        git: {
            commit: Injected<typeof import("./git/commit").default>;
            push: Injected<typeof import("./git/push").default>;
            run: Injected<typeof import("./git/run").default>;
            stage: Injected<typeof import("./git/stage").default>;
            stageCommitPush: Injected<typeof import("./git/stageCommitPush").default>;
            status: Injected<typeof import("./git/status").default>;
        };
        llm: {
            listModels: Injected<typeof import("./llm/listModels").default>;
            parseSSE: Injected<typeof import("./llm/parseSSE").default>;
            refreshClaudeCode: Injected<typeof import("./llm/refreshClaudeCode").default>;
            refreshCodex: Injected<typeof import("./llm/refreshCodex").default>;
            refreshKimiCode: Injected<typeof import("./llm/refreshKimiCode").default>;
            resolveEndpoint: Injected<typeof import("./llm/resolveEndpoint").default>;
            stream: Injected<typeof import("./llm/stream").default>;
            streamAnthropic: Injected<typeof import("./llm/streamAnthropic").default>;
            streamCodex: Injected<typeof import("./llm/streamCodex").default>;
            streamMock: Injected<typeof import("./llm/streamMock").default>;
            streamOpenAI: Injected<typeof import("./llm/streamOpenAI").default>;
            toAnthropicMessages: Injected<typeof import("./llm/toAnthropicMessages").default>;
            toCodexInput: Injected<typeof import("./llm/toCodexInput").default>;
        };
        markdown: {
            highlight: Injected<typeof import("./markdown/highlight").default>;
            mermaid: Injected<typeof import("./markdown/mermaid").default>;
            render: Injected<typeof import("./markdown/render").default>;
        };
        nav: {
            items: Injected<typeof import("./nav/items").default>;
        };
        procs: {
            auth: {
                authenticate: Injected<typeof import("./procs/auth/authenticate").default>;
                cookie: Injected<typeof import("./procs/auth/cookie").default>;
                keys: Injected<typeof import("./procs/auth/keys").default>;
                sign: Injected<typeof import("./procs/auth/sign").default>;
                verify: Injected<typeof import("./procs/auth/verify").default>;
            };
            boot: {
                load: Injected<typeof import("./procs/boot/load").default>;
            };
            cli: {
                list: Injected<typeof import("./procs/cli/list").default>;
                parse: Injected<typeof import("./procs/cli/parse").default>;
                run: Injected<typeof import("./procs/cli/run").default>;
            };
            config: {
                coerce: Injected<typeof import("./procs/config/coerce").default>;
                resolve: Injected<typeof import("./procs/config/resolve").default>;
                validate: Injected<typeof import("./procs/config/validate").default>;
            };
            db: {
                close: Injected<typeof import("./procs/db/close").default>;
                conn: Injected<typeof import("./procs/db/conn").default>;
                exec: Injected<typeof import("./procs/db/exec").default>;
                insert: Injected<typeof import("./procs/db/insert").default>;
                q: Injected<typeof import("./procs/db/q").default>;
                run: Injected<typeof import("./procs/db/run").default>;
                select: Injected<typeof import("./procs/db/select").default>;
                sql: Injected<typeof import("./procs/db/sql").default>;
                toPg: Injected<typeof import("./procs/db/toPg").default>;
                url: Injected<typeof import("./procs/db/url").default>;
            };
            dev: {
                build: Injected<typeof import("./procs/dev/build").default>;
                def: Injected<typeof import("./procs/dev/def").default>;
                doc: Injected<typeof import("./procs/dev/doc").default>;
                genTypes: Injected<typeof import("./procs/dev/genTypes").default>;
                lint: Injected<typeof import("./procs/dev/lint").default>;
                manifest: Injected<typeof import("./procs/dev/manifest").default>;
                route: Injected<typeof import("./procs/dev/route").default>;
                sync: Injected<typeof import("./procs/dev/sync").default>;
                test: Injected<typeof import("./procs/dev/test").default>;
                typecheck: Injected<typeof import("./procs/dev/typecheck").default>;
                watch: Injected<typeof import("./procs/dev/watch").default>;
                where: Injected<typeof import("./procs/dev/where").default>;
            };
            env: {
                fork: Injected<typeof import("./procs/env/fork").default>;
                mode: Injected<typeof import("./procs/env/mode").default>;
                pick: Injected<typeof import("./procs/env/pick").default>;
            };
            events: {
                emit: Injected<typeof import("./procs/events/emit").default>;
                join: Injected<typeof import("./procs/events/join").default>;
                presence: Injected<typeof import("./procs/events/presence").default>;
                reload: Injected<typeof import("./procs/events/reload").default>;
                subscribe: Injected<typeof import("./procs/events/subscribe").default>;
            };
            generate: {
                fn: Injected<typeof import("./procs/generate/fn").default>;
                module: Injected<typeof import("./procs/generate/module").default>;
                repl: Injected<typeof import("./procs/generate/repl").default>;
                route: Injected<typeof import("./procs/generate/route").default>;
            };
            hooks: {
                first: Injected<typeof import("./procs/hooks/first").default>;
                list: Injected<typeof import("./procs/hooks/list").default>;
                register: Injected<typeof import("./procs/hooks/register").default>;
                run: Injected<typeof import("./procs/hooks/run").default>;
            };
            http: {
                dispatch: Injected<typeof import("./procs/http/dispatch").default>;
                loadRoutes: Injected<typeof import("./procs/http/loadRoutes").default>;
                match: Injected<typeof import("./procs/http/match").default>;
                middleware: Injected<typeof import("./procs/http/middleware").default>;
                toResponse: Injected<typeof import("./procs/http/toResponse").default>;
            };
            lifecycle: {
                declared: Injected<typeof import("./procs/lifecycle/declared").default>;
                order: Injected<typeof import("./procs/lifecycle/order").default>;
                start: Injected<typeof import("./procs/lifecycle/start").default>;
                stop: Injected<typeof import("./procs/lifecycle/stop").default>;
            };
            log: {
                debug: Injected<typeof import("./procs/log/debug").default>;
                emit: Injected<typeof import("./procs/log/emit").default>;
                error: Injected<typeof import("./procs/log/error").default>;
                info: Injected<typeof import("./procs/log/info").default>;
                level: Injected<typeof import("./procs/log/level").default>;
                warn: Injected<typeof import("./procs/log/warn").default>;
            };
            migrate: {
                down: Injected<typeof import("./procs/migrate/down").default>;
                status: Injected<typeof import("./procs/migrate/status").default>;
                up: Injected<typeof import("./procs/migrate/up").default>;
            };
            modules: {
                add: Injected<typeof import("./procs/modules/add").default>;
                catalog: Injected<typeof import("./procs/modules/catalog").default>;
                describe: Injected<typeof import("./procs/modules/describe").default>;
                discover: Injected<typeof import("./procs/modules/discover").default>;
                fetch: Injected<typeof import("./procs/modules/fetch").default>;
                link: Injected<typeof import("./procs/modules/link").default>;
                linkAll: Injected<typeof import("./procs/modules/linkAll").default>;
                list: Injected<typeof import("./procs/modules/list").default>;
                panel: Injected<typeof import("./procs/modules/panel").default>;
                paths: Injected<typeof import("./procs/modules/paths").default>;
                readDeclared: Injected<typeof import("./procs/modules/readDeclared").default>;
                reload: Injected<typeof import("./procs/modules/reload").default>;
                remove: Injected<typeof import("./procs/modules/remove").default>;
                unlink: Injected<typeof import("./procs/modules/unlink").default>;
            };
            project: {
                classify: Injected<typeof import("./procs/project/classify").default>;
                name: Injected<typeof import("./procs/project/name").default>;
                projectRoot: Injected<typeof import("./procs/project/projectRoot").default>;
                runtimeDir: Injected<typeof import("./procs/project/runtimeDir").default>;
                scan: Injected<typeof import("./procs/project/scan").default>;
                selfUrl: Injected<typeof import("./procs/project/selfUrl").default>;
                workdir: Injected<typeof import("./procs/project/workdir").default>;
            };
            repl: {
                eval: Injected<typeof import("./procs/repl/eval").default>;
                explain: Injected<typeof import("./procs/repl/explain").default>;
                load: Injected<typeof import("./procs/repl/load").default>;
                token: Injected<typeof import("./procs/repl/token").default>;
            };
            styles: {
                build: Injected<typeof import("./procs/styles/build").default>;
                rebuild: Injected<typeof import("./procs/styles/rebuild").default>;
            };
            ui: {
                alert: Injected<typeof import("./procs/ui/alert").default>;
                attr: Injected<typeof import("./procs/ui/attr").default>;
                avatar: Injected<typeof import("./procs/ui/avatar").default>;
                badge: Injected<typeof import("./procs/ui/badge").default>;
                box: Injected<typeof import("./procs/ui/box").default>;
                breadcrumb: Injected<typeof import("./procs/ui/breadcrumb").default>;
                button: Injected<typeof import("./procs/ui/button").default>;
                card: Injected<typeof import("./procs/ui/card").default>;
                checkboxGroup: Injected<typeof import("./procs/ui/checkboxGroup").default>;
                code: Injected<typeof import("./procs/ui/code").default>;
                combobox: Injected<typeof import("./procs/ui/combobox").default>;
                comboboxChosen: Injected<typeof import("./procs/ui/comboboxChosen").default>;
                comboboxResults: Injected<typeof import("./procs/ui/comboboxResults").default>;
                control: Injected<typeof import("./procs/ui/control").default>;
                descriptionList: Injected<typeof import("./procs/ui/descriptionList").default>;
                dialog: Injected<typeof import("./procs/ui/dialog").default>;
                diff: Injected<typeof import("./procs/ui/diff").default>;
                empty: Injected<typeof import("./procs/ui/empty").default>;
                escape: Injected<typeof import("./procs/ui/escape").default>;
                field: Injected<typeof import("./procs/ui/field").default>;
                form: Injected<typeof import("./procs/ui/form").default>;
                frame: Injected<typeof import("./procs/ui/frame").default>;
                heading: Injected<typeof import("./procs/ui/heading").default>;
                inputGroup: Injected<typeof import("./procs/ui/inputGroup").default>;
                layout: Injected<typeof import("./procs/ui/layout").default>;
                log: Injected<typeof import("./procs/ui/log").default>;
                menu: Injected<typeof import("./procs/ui/menu").default>;
                notFound: Injected<typeof import("./procs/ui/notFound").default>;
                notice: Injected<typeof import("./procs/ui/notice").default>;
                page: Injected<typeof import("./procs/ui/page").default>;
                pagination: Injected<typeof import("./procs/ui/pagination").default>;
                progress: Injected<typeof import("./procs/ui/progress").default>;
                radioGroup: Injected<typeof import("./procs/ui/radioGroup").default>;
                range: Injected<typeof import("./procs/ui/range").default>;
                row: Injected<typeof import("./procs/ui/row").default>;
                segmented: Injected<typeof import("./procs/ui/segmented").default>;
                select: Injected<typeof import("./procs/ui/select").default>;
                skeleton: Injected<typeof import("./procs/ui/skeleton").default>;
                slider: Injected<typeof import("./procs/ui/slider").default>;
                sparkline: Injected<typeof import("./procs/ui/sparkline").default>;
                stat: Injected<typeof import("./procs/ui/stat").default>;
                stats: Injected<typeof import("./procs/ui/stats").default>;
                statusDot: Injected<typeof import("./procs/ui/statusDot").default>;
                steps: Injected<typeof import("./procs/ui/steps").default>;
                subnav: Injected<typeof import("./procs/ui/subnav").default>;
                table: Injected<typeof import("./procs/ui/table").default>;
                tags: Injected<typeof import("./procs/ui/tags").default>;
                textarea: Injected<typeof import("./procs/ui/textarea").default>;
                timeline: Injected<typeof import("./procs/ui/timeline").default>;
                toggle: Injected<typeof import("./procs/ui/toggle").default>;
                toolbar: Injected<typeof import("./procs/ui/toolbar").default>;
                tooltip: Injected<typeof import("./procs/ui/tooltip").default>;
                tree: Injected<typeof import("./procs/ui/tree").default>;
            };
        };
        repl: {
            diagnoseParse: Injected<typeof import("./repl/diagnoseParse").default>;
            eval: Injected<typeof import("./repl/eval").default>;
        };
        screen: {
            click: Injected<typeof import("./screen/click").default>;
            eval: Injected<typeof import("./screen/eval").default>;
            fill: Injected<typeof import("./screen/fill").default>;
            open: Injected<typeof import("./screen/open").default>;
            openTab: Injected<typeof import("./screen/openTab").default>;
            point: Injected<typeof import("./screen/point").default>;
            readScreen: Injected<typeof import("./screen/readScreen").default>;
            say: Injected<typeof import("./screen/say").default>;
            step: Injected<typeof import("./screen/step").default>;
            submit: Injected<typeof import("./screen/submit").default>;
            tabs: Injected<typeof import("./screen/tabs").default>;
            text: Injected<typeof import("./screen/text").default>;
            where: Injected<typeof import("./screen/where").default>;
        };
        session: {
            appendAssistantEvent: Injected<typeof import("./session/appendAssistantEvent").default>;
            appendAssistantMessage: Injected<typeof import("./session/appendAssistantMessage").default>;
            appendErrorEvent: Injected<typeof import("./session/appendErrorEvent").default>;
            appendEvent: Injected<typeof import("./session/appendEvent").default>;
            appendEventWithHtml: Injected<typeof import("./session/appendEventWithHtml").default>;
            appendMessage: Injected<typeof import("./session/appendMessage").default>;
            appendThinkingEvent: Injected<typeof import("./session/appendThinkingEvent").default>;
            appendToolCallEvent: Injected<typeof import("./session/appendToolCallEvent").default>;
            appendUserMessage: Injected<typeof import("./session/appendUserMessage").default>;
            archive: Injected<typeof import("./session/archive").default>;
            collapseFailures: Injected<typeof import("./session/collapseFailures").default>;
            delete: Injected<typeof import("./session/delete").default>;
            deleteMessageAt: Injected<typeof import("./session/deleteMessageAt").default>;
            forAgent: Injected<typeof import("./session/forAgent").default>;
            fork: Injected<typeof import("./session/fork").default>;
            getEvents: Injected<typeof import("./session/getEvents").default>;
            getFullMessages: Injected<typeof import("./session/getFullMessages").default>;
            getMaxEventIdx: Injected<typeof import("./session/getMaxEventIdx").default>;
            getMessages: Injected<typeof import("./session/getMessages").default>;
            list: Injected<typeof import("./session/list").default>;
            load: Injected<typeof import("./session/load").default>;
            loadAll: Injected<typeof import("./session/loadAll").default>;
            replaceEvents: Injected<typeof import("./session/replaceEvents").default>;
            replaceMessages: Injected<typeof import("./session/replaceMessages").default>;
            save: Injected<typeof import("./session/save").default>;
            search: Injected<typeof import("./session/search").default>;
            searchBm25: Injected<typeof import("./session/searchBm25").default>;
            setTitle: Injected<typeof import("./session/setTitle").default>;
            syncAgentState: Injected<typeof import("./session/syncAgentState").default>;
            truncateMessagesFrom: Injected<typeof import("./session/truncateMessagesFrom").default>;
            updateScratchpad: Injected<typeof import("./session/updateScratchpad").default>;
        };
        settings: {
            agentDebounceMs: Injected<typeof import("./settings/agentDebounceMs").default>;
            declared: Injected<typeof import("./settings/declared").default>;
            get: Injected<typeof import("./settings/get").default>;
            getNumber: Injected<typeof import("./settings/getNumber").default>;
            getString: Injected<typeof import("./settings/getString").default>;
            list: Injected<typeof import("./settings/list").default>;
            logoutCodex: Injected<typeof import("./settings/logoutCodex").default>;
            logoutKimi: Injected<typeof import("./settings/logoutKimi").default>;
            modelDefault: Injected<typeof import("./settings/modelDefault").default>;
            remove: Injected<typeof import("./settings/remove").default>;
            renderDeclaredForm: Injected<typeof import("./settings/renderDeclaredForm").default>;
            saveEnv: Injected<typeof import("./settings/saveEnv").default>;
            set: Injected<typeof import("./settings/set").default>;
            startCodexLogin: Injected<typeof import("./settings/startCodexLogin").default>;
            startKimiLogin: Injected<typeof import("./settings/startKimiLogin").default>;
            status: Injected<typeof import("./settings/status").default>;
        };
        skill: {
            greet: Injected<typeof import("../.hyper/skill/greet").default>;
            hello: Injected<typeof import("./skill/hello").default>;
            inspect: Injected<typeof import("./skill/inspect").default>;
            uptime: Injected<typeof import("../.hyper/skill/uptime").default>;
            wordCount: Injected<typeof import("./skill/wordCount").default>;
        };
        tools: {
            dice: Injected<typeof import("./tools/dice").default>;
            password: Injected<typeof import("./tools/password").default>;
        };
        tour: {
            play: Injected<typeof import("./tour/play").default>;
            review: Injected<typeof import("./tour/review").default>;
        };
        ui: {
            action: Injected<typeof import("./ui/action").default>;
            chatColumn: Injected<typeof import("./ui/chatColumn").default>;
            controlScript: Injected<typeof import("./ui/controlScript").default>;
            createAgent: Injected<typeof import("./ui/createAgent").default>;
            eval: Injected<typeof import("./ui/eval").default>;
            layout: Injected<typeof import("./ui/layout").default>;
            navMenu: Injected<typeof import("./ui/navMenu").default>;
            notify: Injected<typeof import("./ui/notify").default>;
            openAgent: Injected<typeof import("./ui/openAgent").default>;
            openFile: Injected<typeof import("./ui/openFile").default>;
            pending: Injected<typeof import("./ui/pending").default>;
            script: Injected<typeof import("./ui/script").default>;
            sendToAgent: Injected<typeof import("./ui/sendToAgent").default>;
            topbar: Injected<typeof import("./ui/topbar").default>;
        };
        workspace: {
            get: Injected<typeof import("./workspace/get").default>;
            normalize: Injected<typeof import("./workspace/normalize").default>;
            resolve: Injected<typeof import("./workspace/resolve").default>;
            set: Injected<typeof import("./workspace/set").default>;
        };
    }

    namespace types {
        namespace agent {
            type Agent = import("./agent/Agent").Agent;
            type MarkerCall = import("./agent/MarkerCall").MarkerCall;
            type MarkerParseError = import("./agent/MarkerParseError").MarkerParseError;
        }
        namespace dev {
            type TestRun = import("./dev/TestRun").TestRun;
        }
        namespace events {
            type Event = import("./events/Event").Event;
        }
        namespace files {
            type EditHashlineOp = import("./files/EditHashlineOp").EditHashlineOp;
            type GrepMatch = import("./files/GrepMatch").GrepMatch;
            type ReadAnchorLine = import("./files/ReadAnchorLine").ReadAnchorLine;
            type ReadHashlineResult = import("./files/ReadHashlineResult").ReadHashlineResult;
        }
        namespace git {
            type Result = import("./git/Result").Result;
        }
        namespace nav {
            type Item = import("./nav/Item").Item;
        }
        namespace procs {
            namespace auth {
                type State = import("./procs/auth/State").State;
            }
            namespace boot {
                type State = import("./procs/boot/State").State;
            }
            namespace cli {
                type State = import("./procs/cli/State").State;
            }
            namespace config {
                type State = import("./procs/config/State").State;
            }
            namespace db {
                type Query = import("./procs/db/Query").Query;
                type State = import("./procs/db/State").State;
            }
            namespace dev {
                type State = import("./procs/dev/State").State;
            }
            namespace events {
                type State = import("./procs/events/State").State;
            }
            namespace hooks {
                type State = import("./procs/hooks/State").State;
            }
            namespace http {
                type State = import("./procs/http/State").State;
            }
            namespace lifecycle {
                type State = import("./procs/lifecycle/State").State;
            }
            namespace log {
                type LogRecord = import("./procs/log/LogRecord").LogRecord;
                type State = import("./procs/log/State").State;
            }
            namespace migrate {
                type State = import("./procs/migrate/State").State;
            }
            namespace modules {
                type State = import("./procs/modules/State").State;
            }
            namespace project {
                type State = import("./procs/project/State").State;
            }
            namespace repl {
                type State = import("./procs/repl/State").State;
            }
            namespace styles {
                type State = import("./procs/styles/State").State;
            }
        }
        namespace screen {
            type Catalogue = import("./screen/Catalogue").Catalogue;
            type Descriptor = import("./screen/Descriptor").Descriptor;
            type State = import("./screen/State").State;
        }
        namespace session {
            type Bm25Hit = import("./session/Bm25Hit").Bm25Hit;
        }
        namespace tools {
            type DiceOpts = import("./tools/DiceOpts").DiceOpts;
            type PasswordOpts = import("./tools/PasswordOpts").PasswordOpts;
        }
        namespace tour {
            type Step = import("./tour/Step").Step;
        }
        namespace ui {
            type AgentLaunch = import("./ui/AgentLaunch").AgentLaunch;
        }
    }

    interface CtxState {
        procs: {
            auth: import("./procs/auth/State").State;
            boot: import("./procs/boot/State").State;
            cli: import("./procs/cli/State").State;
            config: import("./procs/config/State").State;
            db: import("./procs/db/State").State;
            dev: import("./procs/dev/State").State;
            events: import("./procs/events/State").State;
            hooks: import("./procs/hooks/State").State;
            http: import("./procs/http/State").State;
            lifecycle: import("./procs/lifecycle/State").State;
            log: import("./procs/log/State").State;
            migrate: import("./procs/migrate/State").State;
            modules: import("./procs/modules/State").State;
            project: import("./procs/project/State").State;
            repl: import("./procs/repl/State").State;
            styles: import("./procs/styles/State").State;
        };
        screen: import("./screen/State").State;
    }

    type Session = import("./Session").Session;
}
export {};
