// Auto-generated by ctx.genTypes — do not edit
declare global {
    type Context = import("./$type_Context").Context;

    interface FnsRegistry {
        agent: {
        clear: typeof import("./agent/clear").default;
        compact: typeof import("./agent/compact").default;
        run: typeof import("./agent/run").default;
        start: typeof import("./agent/start").default;
        stop: typeof import("./agent/stop").default;
        stream: typeof import("./agent/stream").default;
        systemPrompt: typeof import("./agent/systemPrompt").default;
        };
        db: {
        connect: typeof import("./db/connect").default;
        exec: typeof import("./db/exec").default;
        insert: typeof import("./db/insert").default;
        migrate: typeof import("./db/migrate").default;
        select: typeof import("./db/select").default;
        };
        http: {
        loadRoutes: typeof import("./http/loadRoutes").default;
        match: typeof import("./http/match").default;
        start: typeof import("./http/$start").default;
        };
        markdown: {
        highlight: typeof import("./markdown/highlight").default;
        render: typeof import("./markdown/render").default;
        };
        memory: {
        delete: typeof import("../.hyper/memory/delete").default;
        init: typeof import("../.hyper/memory/init").default;
        read: typeof import("../.hyper/memory/read").default;
        search: typeof import("../.hyper/memory/search").default;
        store: typeof import("../.hyper/memory/store").default;
        };
        repl: {
        eval: typeof import("./repl/eval").default;
        load: typeof import("./repl/load").default;
        start: typeof import("./repl/$start").default;
        };
        session: {
        delete: typeof import("./session/delete").default;
        list: typeof import("./session/list").default;
        load: typeof import("./session/load").default;
        loadAll: typeof import("./session/loadAll").default;
        save: typeof import("./session/save").default;
        search: typeof import("./session/search").default;
        };
        skill: {
        hello: typeof import("../.hyper/skill/hello").default;
        wordCount: typeof import("../.hyper/skill/wordCount").default;
        };
        tools: {
        dice: typeof import("../.hyper/tools/dice").default;
        password: typeof import("../.hyper/tools/password").default;
        };
        ui: {
        layout: typeof import("./ui/layout").default;
        script: typeof import("./ui/script").default;
        };
    }

    interface RootFns {
    genTypes: typeof import("./genTypes").default;
    loadFns: typeof import("./loadFns").default;
    }

    namespace types {
        namespace agent {
            type Agent = import("./agent/$type_Agent").Agent;
        }
        namespace memory {
            type Entry = import("../.hyper/memory/$type_Entry").Entry;
        }
        namespace tools {
            type DiceOpts = import("../.hyper/tools/$type_DiceOpts").DiceOpts;
            type PasswordOpts = import("../.hyper/tools/$type_PasswordOpts").PasswordOpts;
        }
    }
}
export {};
