import { Glob } from "bun";
import { resolve, dirname, basename } from "node:path";

export default async function (_ctx: Context) {
    const srcDir = import.meta.dir;
    const hyperDir = resolve(srcDir, "..", ".hyper");

    const globals: string[] = [];
    const typesByModule: Record<string, string[]> = {};
    const fnsByModule: Record<string, string[]> = {};
    const rootFns: string[] = [];

    for (const root of [srcDir, hyperDir]) {
        const exists = await Bun.file(root).stat().then(() => true).catch(() => false);
        if (!exists) continue;
        const importPrefix = root === hyperDir ? "../.hyper/" : "./";
        const glob = new Glob("**/*.ts");
        for await (const file of glob.scan(root)) {
            if (shouldSkip(file)) continue;
            const moduleDir = dirname(file);
            const fileName = basename(file, ".ts");
            const importPath = importPrefix + file.slice(0, -".ts".length);

            if (fileName.startsWith("$type_")) {
                const typeName = fileName.slice("$type_".length);
                if (!typeName) continue;
                const line = `type ${typeName} = import("${importPath}").${typeName};`;
                if (moduleDir === ".") {
                    globals.push(`    ${line}`);
                } else {
                    typesByModule[moduleDir] = typesByModule[moduleDir] || [];
                    typesByModule[moduleDir].push(`            ${line}`);
                }
                continue;
            }

            const fnName = fileName.startsWith("$") ? fileName.slice(1) : fileName;
            const entry = `${fnName}: typeof import("${importPath}").default;`;
            if (moduleDir === ".") {
                rootFns.push(`    ${entry}`);
            } else {
                fnsByModule[moduleDir] = fnsByModule[moduleDir] || [];
                fnsByModule[moduleDir].push(`        ${entry}`);
            }
        }
    }

    const lines: string[] = [
        "// Auto-generated by ctx.genTypes — do not edit",
        "declare global {",
        ...globals,
        "",
        "    interface FnsRegistry {",
    ];
    for (const [mod, entries] of Object.entries(fnsByModule).sort()) {
        lines.push(`        ${mod}: {`);
        lines.push(...entries.sort());
        lines.push(`        };`);
    }
    lines.push("    }", "", "    interface RootFns {");
    lines.push(...rootFns.sort());
    lines.push("    }");

    if (Object.keys(typesByModule).length > 0) {
        lines.push("", "    namespace types {");
        for (const [mod, entries] of Object.entries(typesByModule).sort()) {
            lines.push(`        namespace ${mod} {`);
            lines.push(...entries.sort());
            lines.push("        }");
        }
        lines.push("    }");
    }

    lines.push("}", "export {};", "");

    const out = resolve(srcDir, "ctx_ns.d.ts");
    await Bun.write(out, lines.join("\n"));
    const typesCount = globals.length + Object.values(typesByModule).flat().length;
    console.log(`[genTypes] ${rootFns.length} root fn(s), ${Object.keys(fnsByModule).length} module(s), ${typesCount} type(s) → src/ctx_ns.d.ts`);
    return { roots: rootFns.length, modules: Object.keys(fnsByModule).length, types: typesCount };
}

function shouldSkip(file: string): boolean {
    if (file.endsWith(".test.ts") || file.endsWith(".d.ts")) return true;
    if (file.endsWith(".entry.ts")) return true; // browser-only bundle entry
    const name = basename(file, ".ts");
    if (name === "$main" || name === "$test") return true;
    if (name.startsWith("$route_")) return true;
    return false;
}
