/** GET /news — Hyper-native durable news reader and archive. */
export default async function(ctx:Context,_session:Session|null,opts:{req:Request;params:Record<string,string>}){
 const esc=(v:any)=>ctx.fns.procs.ui.escape({text:String(v??"")}),u=new URL(opts.req.url),q=(u.searchParams.get("q")??"").trim(),source=u.searchParams.get("source")??"",view=u.searchParams.get("view")??"unread",offset=Math.max(0,Number(u.searchParams.get("offset")??0));
 const [stats,sources,rows]=await Promise.all([ctx.fns.news.stats({}),ctx.fns.news.sources({}),ctx.fns.news.list({query:q||undefined,source:source||undefined,unread:view==='unread'?true:undefined,liked:view==='liked'?true:undefined,limit:30,offset})]);
 const href=(change:Record<string,string|number>)=>{const p=new URLSearchParams();const x={q,source,view,...change};for(const[k,v]of Object.entries(x))if(v!==""&&v!=="all"&&v!==0)p.set(k,String(v));const s=p.toString();return s?`/news?${s}`:"/news"};
 const tabs=[["unread","Unread",stats.unread],["all","Archive",stats.total],["liked","Liked",stats.liked]].map(([key,label,n])=>`<a href="${href({view:String(key),offset:0})}" class="rounded-lg px-3 py-2 text-xs font-medium ${view===key?"bg-primary text-primary-content":"hover:bg-base-200 text-base-content/60"}">${label} <span class="ml-1 opacity-70">${n}</span></a>`).join("");
 const chips=sources.map((s:any)=>`<a href="${href({source:s.source===source?"":s.source,offset:0})}" class="inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[11px] ${s.source===source?"border-primary bg-primary/10 text-primary":"border-base-300 hover:bg-base-200"}">${esc(s.source)} <b>${s.total}</b></a>`).join("");
 const cards=rows.map((r:any)=>{const date=new Date(r.shown_at??r.fetched_at).toISOString().slice(0,10),idPath=[r.source,r.id].map((part:string)=>encodeURIComponent(part)).join('/');return `<article class="border-t border-base-200 px-4 py-4 first:border-t-0 hover:bg-base-200/35"><div class="flex gap-3"><div class="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-xs font-semibold text-primary">${esc(String(r.source).slice(0,2).toUpperCase())}</div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2 text-[11px] text-base-content/40"><span class="font-medium text-base-content/60">${esc(r.source)}</span><span>·</span><time>${date}</time>${r.liked_at?`<i class="ph-fill ph-heart text-rose-500"></i>`:""}${!r.read_at?`<span class="size-1.5 rounded-full bg-primary"></span>`:""}</div><a href="/news/${idPath}" class="mt-1 block text-base font-semibold leading-6 hover:text-primary">${esc(r.title)}</a>${r.summary?`<p class="mt-2 line-clamp-3 text-sm leading-6 text-base-content/55">${esc(r.summary)}</p>`:""}<div class="mt-3 flex items-center gap-3 text-xs text-base-content/40">${r.points!=null?`<span><i class="ph ph-arrow-up"></i> ${r.points}</span>`:""}${r.comments!=null?`<span><i class="ph ph-chat-circle"></i> ${r.comments}</span>`:""}${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noreferrer" class="ml-auto text-primary hover:underline">Original <i class="ph ph-arrow-square-out"></i></a>`:""}</div></div></div></article>`}).join("");
 return {title:"News",main:`<div class="mx-auto w-full max-w-5xl p-5 sm:p-8"><header class="flex flex-wrap items-end justify-between gap-4"><div><div class="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-[.18em] text-primary"><i class="ph ph-newspaper"></i>Core archive</div><h1 class="text-3xl font-semibold tracking-tight">News</h1><p class="mt-2 text-sm text-base-content/55">Stored stories and prepared summaries. No feeds or jobs run here.</p></div><div class="flex flex-wrap items-center gap-2">${ctx.fns.procs.ui.button({action:"reader",label:"Reader",html:`<i class="ph ph-presentation"></i><span>Reader</span><kbd class="kbd kbd-xs">J</kbd>`,href:`/news/reader?source=${encodeURIComponent(source)}&q=${encodeURIComponent(q)}&unread=${view==='unread'?1:0}`,tone:"default"})}${tabs}</div></header><form class="mt-6 flex gap-2"><input type="hidden" name="view" value="${esc(view)}">${source?`<input type="hidden" name="source" value="${esc(source)}">`:""}<label class="relative flex-1"><i class="ph ph-magnifying-glass absolute left-3 top-1/2 -translate-y-1/2 text-base-content/35"></i><input name="q" value="${esc(q)}" placeholder="Search the archive" class="w-full rounded-xl border border-base-300 bg-base-100 py-3 pl-10 pr-4 text-sm outline-none focus:border-primary"></label><button class="rounded-xl bg-primary px-5 text-sm font-medium text-primary-content">Search</button></form><div class="mt-4 flex flex-wrap gap-1.5">${chips}</div><section class="mt-6 overflow-hidden rounded-xl border border-base-300 bg-base-100 shadow-sm">${cards||`<div class="p-12 text-center text-sm text-base-content/45">No stored stories match this view.</div>`}</section><div class="mt-4 flex justify-end gap-2">${offset?`<a href="${href({offset:Math.max(0,offset-30)})}" class="rounded-lg border border-base-300 px-3 py-2 text-xs">Newer</a>`:""}${rows.length===30?`<a href="${href({offset:offset+30})}" class="rounded-lg border border-base-300 px-3 py-2 text-xs">Older</a>`:""}</div></div>`};
}
