/** GET /news/reader/at — renders one cursor-positioned reader card and controls. */
export default async function(ctx:Context,_session:Session|null,opts:{req:Request;params:Record<string,string>}){
 const esc=(v:any)=>ctx.fns.procs.ui.escape({text:String(v??"")}),u=new URL(opts.req.url),cur=u.searchParams.get("id")??"",source=u.searchParams.get("source")??"",q=(u.searchParams.get("q")??"").trim(),unread=u.searchParams.get("unread")!=="0";
 const where:string[]=[],base:any[]=[];if(source){where.push("source=?");base.push(source)}if(q){where.push("search_vector @@ websearch_to_tsquery('simple',?)");base.push(q)}if(unread)where.push("read_at IS NULL");
 const condition=where.length?`WHERE ${where.join(" AND ")}`:"",order="coalesce(shown_at,fetched_at)";
 let item:any;if(cur)item=(await ctx.fns.procs.db.select({sql:"SELECT * FROM news.items WHERE id=?",params:[cur]}))[0];if(!item)item=(await ctx.fns.procs.db.select({sql:`SELECT * FROM news.items ${condition} ORDER BY ${order} DESC LIMIT 1`,params:base}))[0];
 if(!item)return `<main id="reader" class="flex flex-1 items-center justify-center"><div class="max-w-md text-center">${ctx.fns.procs.ui.empty({title:"Nothing to read",message:"This filter has no stored stories."})}</div></main>`;
 await ctx.fns.news.setRead({ids:[item.id]});
 const neighbors=async(dir:"prev"|"next")=>{const before=dir==="next";const c=[...where,`${order} ${before?"<":">"} ?::timestamptz`],p=[...base,new Date(item.shown_at??item.fetched_at).toISOString()];return (await ctx.fns.procs.db.select({sql:`SELECT id FROM news.items WHERE ${c.join(" AND ")} ORDER BY ${order} ${before?"DESC":"ASC"} LIMIT 1`,params:p}))[0]?.id??""};
 const [prev,next,stats]=await Promise.all([neighbors("prev"),neighbors("next"),ctx.fns.news.stats({})]);
 const qp=(id:string)=>{const p=new URLSearchParams({id,source,q,unread:unread?"1":"0"});return `/news/reader/at?${p}`},push=(id:string)=>{const p=new URLSearchParams({id,source,q,unread:unread?"1":"0"});return `/news/reader?${p}`};
 const prevButton=ctx.fns.procs.ui.button({action:"previous",label:"Previous",html:`<i class="ph ph-arrow-left"></i><span>Previous</span><kbd class="kbd kbd-xs">K</kbd>`,get:qp(prev),target:"#reader",swap:"outerHTML",disabled:!prev,attrs:prev?{"hx-push-url":push(prev),id:"reader-prev"}:{id:"reader-prev"}});
 const nextButton=ctx.fns.procs.ui.button({action:"next",label:"Next",html:`<span>Next</span><kbd class="kbd kbd-xs">J</kbd><i class="ph ph-arrow-right"></i>`,get:qp(next),target:"#reader",swap:"outerHTML",tone:"primary",disabled:!next,attrs:next?{"hx-push-url":push(next),id:"reader-next"}:{id:"reader-next"}});
 const likeButton=ctx.fns.procs.ui.button({action:"like",label:item.liked_at?"Unlike":"Like",html:`<i class="${item.liked_at?"ph-fill":"ph"} ph-heart"></i><span>${item.liked_at?"Liked":"Like"}</span><kbd class="kbd kbd-xs">L</kbd>`,post:"/news/like",vals:{id:item.id,liked:!item.liked_at},target:"#reader",swap:"outerHTML",tone:item.liked_at?"danger":"default",attrs:{id:"reader-like"}});
 const original=ctx.fns.procs.ui.button({action:"original",label:"Original",html:`<span>Original</span><kbd class="kbd kbd-xs">Enter</kbd><i class="ph ph-arrow-square-out"></i>`,href:item.url||`/news/${[item.source,item.id].map(encodeURIComponent).join('/')}`,attrs:{id:"reader-original",target:item.url?"_blank":undefined,rel:item.url?"noreferrer":undefined}});
 const raw=String(item.summary??"").trim();const paragraphs=raw.split(/\n\s*\n/).map((part:string)=>part.trim()).filter(Boolean);const short=paragraphs[0]??"";const remainder=paragraphs.slice(1).join("\n\n");const long=[remainder,item.summary_long,item.article_md].filter(Boolean).join("\n\n");
 const topics=ctx.fns.procs.ui.tags({items:(item.topics??[]).map((label:string)=>({label}))});const date=new Date(item.shown_at??item.fetched_at).toISOString().slice(0,10);
 const toolbar=ctx.fns.procs.ui.toolbar({left:`${ctx.fns.procs.ui.badge({text:item.source_label??item.source,tone:"info"})}<span class="text-xs text-base-content/45">${date}${item.author?` · ${esc(item.author)}`:""}</span><a href="/news?view=unread" class="badge badge-soft badge-sm ${stats.unread?"badge-warning":"badge-success"}"><i class="ph ph-envelope-simple"></i>${stats.unread} unread</a>`,right:original});
 const targets=await ctx.fns.news.shareTargets({});let share="";if(targets.length){const first=targets[0]!;share=`<div class="border-t border-base-200 px-4 py-3"><div id="reader-share-picker" hx-get="/news/share/picker?id=${encodeURIComponent(item.id)}&target=${encodeURIComponent(first.target)}" hx-trigger="load" hx-swap="innerHTML"></div><div id="reader-share-result"></div></div>`}
 const agentLaunch=`<form hx-post="/news/agent" hx-swap="none" class="flex min-w-0 flex-1 items-center gap-2"><input type="hidden" name="id" value="${esc(item.id)}"><label class="relative min-w-48 max-w-md flex-1"><span class="pointer-events-none absolute inset-y-0 left-0 flex w-9 items-center justify-center"><i class="ph ph-sparkle text-base-content/35 leading-none"></i></span><input name="prompt" value="Краткий пересказ" class="h-8 w-full rounded-lg border border-base-300 bg-base-100 pl-9 pr-3 text-xs outline-none focus:border-primary" aria-label="Agent task"></label><button class="ui-button ui-button--sm ui-button--default shrink-0" type="submit"><i class="ph ph-robot"></i><span>Start agent</span></button></form>`;
 const card=ctx.fns.procs.ui.card({class:"w-full shadow-lg",body:`${toolbar}<div class="mx-auto flex min-h-[55vh] max-w-4xl flex-col justify-center py-5 sm:py-8"><h2 class="text-balance text-center text-2xl font-semibold leading-tight tracking-tight sm:text-4xl">${esc(item.title)}</h2>${topics?`<div class="mt-4 flex justify-center">${topics}</div>`:""}${item.image_url?`<img src="${esc(item.image_url)}" alt="" class="mx-auto mt-6 max-h-[42vh] max-w-full rounded-2xl object-contain">`:""}<div class="news-reader-copy mx-auto mt-7 max-w-3xl whitespace-pre-wrap text-pretty text-center leading-relaxed text-base-content/70">${esc(short)}</div>${long?`<div id="reader-expanded" hidden class="news-reader-copy mx-auto mt-5 max-w-3xl whitespace-pre-wrap border-t border-base-200 pt-5 text-left leading-relaxed text-base-content/65">${esc(long)}</div>`:""}</div>${share}`,footer:`<div class="flex flex-wrap items-center gap-3"><div class="flex gap-2">${likeButton}<a href="/news" class="ui-button ui-button--sm ui-button--ghost"><i class="ph ph-list"></i> News</a></div>${agentLaunch}<div class="ml-auto flex gap-2">${prevButton}${nextButton}</div></div>`});
 return `<main id="reader" data-id="${esc(item.id)}" class="flex min-h-0 flex-1 items-center justify-center">${card}</main>`;
}
