/** GET /cron — embedded cron management page. */
export default async function (ctx: Context, _session: Session | null, _opts: { req: Request; params: Record<string, string> }) {
    const esc = (value: any) => ctx.fns.procs.ui.escape({ text: String(value ?? "") });
    const field = (label: string, name: string, placeholder: string, required = true) => `<label class="grid gap-1 text-xs font-medium text-base-content/65"><span>${esc(label)}</span><input name="${esc(name)}" placeholder="${esc(placeholder)}" ${required ? "required" : ""} class="rounded-md border border-base-300 bg-base-100 px-3 py-2 font-mono text-xs outline-none focus:border-primary"></label>`;
    const main = `<div class="mx-auto w-full max-w-7xl p-5 sm:p-8">
<div class="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-semibold tracking-tight">Cron tasks</h1><p class="mt-1 text-sm text-base-content/55">Durable interval and one-shot runtime jobs, executed by the embedded worker.</p></div><a href="/functions?namespace=cron" class="rounded-md border border-base-300 px-3 py-2 text-xs hover:bg-base-200">API docs</a></div>
<section class="mb-6 rounded-xl border border-base-300 bg-base-100 p-4 shadow-sm"><h2 class="mb-3 text-sm font-semibold">Schedule task</h2>
<form hx-post="/cron/add" hx-target="#cron-jobs" hx-swap="outerHTML" class="grid gap-3 lg:grid-cols-12">
<div class="lg:col-span-3">${field("Name", "name", "calendar-sync")}</div><div class="lg:col-span-3">${field("Runtime function", "fn", "google.syncCalendar")}</div><div class="lg:col-span-2">${field("Interval", "every", "15m")}</div><div class="lg:col-span-4">${field("Arguments JSON", "args", "{}", false)}</div>
<div class="flex items-center gap-2 lg:col-span-12"><label class="flex items-center gap-2 text-xs text-base-content/65"><input type="checkbox" name="now" value="1" class="checkbox checkbox-xs">Run first occurrence now</label><button class="ml-auto rounded-md bg-primary px-4 py-2 text-xs font-medium text-primary-content hover:opacity-90">Add recurring task</button></div></form>
<details class="mt-4 border-t border-base-200 pt-4"><summary class="cursor-pointer text-xs font-medium text-base-content/65">Schedule one-shot task</summary><form hx-post="/cron/defer" hx-target="#cron-jobs" hx-swap="outerHTML" class="mt-3 grid gap-3 lg:grid-cols-12"><div class="lg:col-span-3">${field("Name", "name", "calendar-once", false)}</div><div class="lg:col-span-3">${field("Runtime function", "fn", "google.syncCalendar")}</div><div class="lg:col-span-2">${field("Run in", "in", "30m")}</div><div class="lg:col-span-4">${field("Arguments JSON", "args", "{}", false)}</div><div class="lg:col-span-12 flex justify-end"><button class="rounded-md border border-primary/30 px-4 py-2 text-xs font-medium text-primary hover:bg-primary/10">Add one-shot task</button></div></form></details></section>
${await ctx.fns.cron.panel({})}</div>`;
    return { title: "cron", main };
}
