import {afterAll,beforeAll,describe,expect,test} from "bun:test";
import {mkTestCtx} from "../_testCtx.entry";
let ctx:any;const names:string[]=[];
beforeAll(async()=>{ctx=await mkTestCtx();await ctx.fns.procs.migrate.up({});ctx.fns.testCron={echo:async(_c:any,_s:any,o:any)=>({value:o.value})};});
afterAll(async()=>{for(const name of names){await ctx.fns.procs.db.run({sql:"DELETE FROM cron_runs WHERE task_name=?",params:[name]});await ctx.fns.procs.db.run({sql:"DELETE FROM cron_tasks WHERE name=?",params:[name]});}await ctx.fns.procs.db.close?.({});});
describe("cron tasks and runs",()=>{
test("add upserts one task",async()=>{const name=`test-add-${crypto.randomUUID()}`;names.push(name);await ctx.fns.cron.add({name,fn:"testCron.echo",every:"1h",args:{value:1}});await ctx.fns.cron.add({name,fn:"testCron.echo",every:"2h",args:{value:2}});const rows=await ctx.fns.procs.db.select({sql:"SELECT every_ms,args FROM cron_tasks WHERE name=?",params:[name]});expect(rows).toHaveLength(1);expect(Number(rows[0].every_ms)).toBe(7200000);expect(rows[0].args.value).toBe(2);});
test("concurrent claim creates one run",async()=>{const name=`test-claim-${crypto.randomUUID()}`;names.push(name);await ctx.fns.cron.defer({name,fn:"testCron.echo",in:-1,args:{value:3}});const[a,b]=await Promise.all([ctx.fns.cron.claim({}),ctx.fns.cron.claim({})]);expect([a,b].filter(Boolean)).toHaveLength(1);const runs=await ctx.fns.procs.db.select({sql:"SELECT id FROM cron_runs WHERE task_name=?",params:[name]});expect(runs).toHaveLength(1);});
test("run records history and advances interval task",async()=>{const name=`test-run-${crypto.randomUUID()}`;names.push(name);await ctx.fns.cron.add({name,fn:"testCron.echo",every:"1s",now:true,args:{value:42}});const run=await ctx.fns.cron.claim({});const result=await ctx.fns.cron.runOne({id:Number(run.id)});expect(result.status).toBe("done");const history=await ctx.fns.cron.runs({name});expect(history[0].result.value).toBe(42);const task=(await ctx.fns.cron.list({name}))[0];expect(task.state).toBe("idle");expect(Number(task.nextRunAt)).toBeGreaterThan(Date.now());});
test("enabled status persists independently",async()=>{const name=`test-enabled-${crypto.randomUUID()}`;names.push(name);await ctx.fns.cron.add({name,fn:"testCron.echo",every:"1h"});await ctx.fns.cron.setEnabled({name,enabled:false});expect((await ctx.fns.cron.list({name}))[0].enabled).toBe(false);await ctx.fns.cron.setEnabled({name,enabled:true});expect((await ctx.fns.cron.list({name}))[0].enabled).toBe(true);});
});
