/**
 * Renders the cron task list management panel.
 * @param opts.message Optional success message.
 * @param opts.error Optional operation error.
 * @param opts.limit Maximum tasks rendered. @default 100 @minimum 1 @maximum 500
 */
export default async function (ctx: Context, _session: Session | null, opts: {
    /** Optional success message. */ message?: string;
    /** Optional operation error. */ error?: string;
    /** Maximum tasks rendered. @default 100 @minimum 1 @maximum 500 */ limit?: number;
}): Promise<string> {
    const esc=(v:any)=>ctx.fns.procs.ui.escape({text:String(v??"")}); const tasks=await ctx.fns.cron.list({limit:opts.limit??100});
    const time=(v:any)=>v==null?"—":new Date(Number(v)).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"medium"});
    const interval=(v:any)=>{let ms=Number(v??0);if(!ms)return"once";const p:string[]=[];for(const[u,s]of[["d",86400000],["h",3600000],["m",60000],["s",1000]]as const){const n=Math.floor(ms/s);if(n){p.push(`${n}${u}`);ms-=n*s;}}return p.join("")||"<1s";};
    const rows=tasks.map((t:any)=>`<tr class="border-t border-base-200 align-top"><td class="px-3 py-3"><a href="/cron/${encodeURIComponent(t.name)}" class="font-medium text-primary hover:underline">${esc(t.name)}</a><div class="mt-1 text-[11px] text-base-content/45">${esc(t.source)}${t.sourceFile?` · ${esc(t.sourceFile)}`:""}</div></td><td class="px-3 py-3"><code class="text-xs">${esc(t.fn)}</code><div class="mt-1 font-mono text-[11px] text-base-content/45">${esc(JSON.stringify(t.args??{}))}</div></td><td class="px-3 py-3"><span class="rounded-full px-2 py-1 text-[11px] ${t.enabled?"bg-success/10 text-success":"bg-base-200 text-base-content/45"}">${t.enabled?"enabled":"disabled"}</span><div class="mt-2 text-[11px] text-base-content/45">${esc(t.state)}</div></td><td class="px-3 py-3 text-xs"><div>${esc(time(t.nextRunAt))}</div><div class="mt-1 text-base-content/45">${esc(interval(t.everyMs))}</div></td><td class="px-3 py-3 text-xs"><div>${esc(t.lastStatus??"never")}</div>${t.lastError?`<div class="mt-1 max-w-64 truncate text-error" title="${esc(t.lastError)}">${esc(String(t.lastError).split("\n")[0])}</div>`:""}</td><td class="px-3 py-3"><div class="flex gap-2"><form hx-post="/cron/run-now" hx-target="#cron-jobs" hx-swap="outerHTML"><input type="hidden" name="name" value="${esc(t.name)}"><button class="rounded border border-base-300 px-2 py-1 text-xs">Run now</button></form><form hx-post="/cron/enabled" hx-target="#cron-jobs" hx-swap="outerHTML"><input type="hidden" name="name" value="${esc(t.name)}"><input type="hidden" name="enabled" value="${t.enabled?"false":"true"}"><button class="rounded border border-base-300 px-2 py-1 text-xs">${t.enabled?"Disable":"Enable"}</button></form></div></td></tr>`).join("");
    return `<section id="cron-jobs" hx-get="/cron/jobs" hx-trigger="every 5s" hx-swap="outerHTML" class="rounded-xl border border-base-300 bg-base-100 shadow-sm">${opts.message?`<div class="border-b border-success/20 bg-success/10 px-4 py-3 text-sm text-success">${esc(opts.message)}</div>`:""}${opts.error?`<div class="border-b border-error/20 bg-error/10 px-4 py-3 text-sm text-error">${esc(opts.error)}</div>`:""}<div class="overflow-x-auto"><table class="w-full min-w-[950px] text-left"><thead class="bg-base-200/60 text-[11px] uppercase text-base-content/45"><tr><th class="px-3 py-2">Task</th><th class="px-3 py-2">Function</th><th class="px-3 py-2">Status</th><th class="px-3 py-2">Next / schedule</th><th class="px-3 py-2">Last run</th><th class="px-3 py-2">Actions</th></tr></thead><tbody>${rows||`<tr><td colspan="6" class="px-4 py-10 text-center text-sm text-base-content/45">No cron tasks yet.</td></tr>`}</tbody></table></div></section>`;
}
